var db_product = [
        { 
			'name':'2016微软技术大会',
			'contenttype': 'article',
			'logo':'event_tech_kv_236x144.jpg',
			'banner':'event_tech_kv_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'',
			'eventtime':'',
			'expirydate':'2016-11-16T14:30:00+08:00',
			'location':'北京国家会议中心',
			'eventfor': ['IT专业人员', '开发人员'],
			'eventtype': ['研讨会及会议'],
			'category': ['线下会议'],
			'product': [''],
			'description': '<p>2016微软技术大会全新开启，携数字的力量蓄势发力，让您把握新的科技大势，与全球顶级技术专家面对面探讨最前沿的数字技术，探索数字化的无限潜能，动手体验获得更多灵感并得以将其付诸行动，尽情感受微软最新科技的魅力。</p><p>十二大精彩课程主题包含一百余场微软重量级课程，让您可以零距离体验到微软的最新技术及解决方案，尽情感受微软科技的魅力。</p>',
			'regurl':'https://channel9.msdn.com/Events/Ignite/Microsoft-Ignite-China-2016?sort=status&direction=desc',
			'gallery': ['']
		},
		{ 
			'name':'微软面向未来的创新学校网络在线研讨会',
			'contenttype': 'article',
			'logo':'future_seminar_236x144.jpg',
			'banner':'future_seminar_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'',
			'eventtime':'',
			'expirydate':'2016-11-16T14:30:00+08:00',
			'location':'在线会议',
			'eventfor': ['业务管理者','IT管理者'],
			'eventtype': ['在线会议回放'],
			'category': ['网络研讨会'],
			'product': ['Devices & Xbox', 'Office', 'Skype', 'Hololens', 'Microsoft Azure'],
			'description': '<p>简单的硬件堆砌、生硬的工作流程、枯燥的教学方式......教育领域中所面临的一系列问题都在周而复始地“上演”着。毫无乐趣的“疲态”教学使“教学相长”愈走愈远。</p><p>善于发现并解决问题的微软决不允许“恶性循环”就这样摆在面前。为倡导《教育信息化“十三五”规划》，更为了解放传统教育系统的“裹脚布”，微软在全球范围内创办了面向未来的创新学校。从应用层、系统层到物理层；从硬件配置到软件培训，微软创新学校提供了完整专业的解决方案，大力推动了教育领域的转型与升级。</p>',
			'regurl':'http://e.vhall.com/360061992?&refer=pc',
			'gallery': ['']
		},
		{ 
			'name':'Office 365云应用创新教学网络在线研讨会',
			'contenttype': 'article',
			'logo':'office_seminar_236x144.jpg',
			'banner':'office_seminar_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'',
			'eventtime':'',
			'expirydate':'2016-11-16T14:30:00+08:00',
			'location':'在线会议',
			'eventfor': ['业务管理者','IT管理者'],
			'eventtype': ['在线会议回放'],
			'category': ['网络研讨会'],
			'product': ['Devices & Xbox', 'Office', 'Skype'],
			'description': '<p>在这新型的信息化时代中，微软凭借其庞大且完善的教育产品体系，为客户提供了专业的服务与方案。Office 365 教育版是微软为教育机构打造的一整套教育云服务，它不仅包含最新版的 Office 软件，同时还能满足教育机构在沟通时的邮件处理和日程安排 （Exchange Online ) ，跨地域的教学信息共享（SharePoint Online），即时消息和在线可视网络教学课堂（Skype for Business）的需求。Office 365 教育版云服务将帮助教育机构实现教学的运维、管理和使用体验的革新，为教育机构带来更灵活、高效、更安全可靠的云教育办公方式。</p>',
			'regurl':'http://e.vhall.com/746416732?&refer=pc',
			'gallery': ['']
		},
		{ 
			'name':'【微软数字化教育创新体验营】广阔天地，无限探索 - Minecraft 以游戏方式创新教学',
			'contenttype': 'article',
			'logo':'numbers talk_236x144.jpg',
			'banner':'numbers talk_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'',
			'eventtime':'',
			'expirydate':'2016-11-16T14:30:00+08:00',
			'location':'在线会议',
			'eventfor': ['业务管理者','IT管理者'],
			'eventtype': ['解决方案演示'],
			'category': ['网络研讨会'],
			'product': ['Office'],
			'description': '<p>Minecraft（我的世界）最初作为一款游戏，一经推出就以独特的「像素化」风格吸引了广大玩家的注意。在被微软收购后发展到今天，扩展性极高的「我的世界」已经不仅仅是一款游戏，在Minecraft的广阔天地中，用户只需要发挥自己想象力，就能将自己的梦想一点一点地实现。也正是被这样的特性吸引，越来越多的学校和教育机构开始考虑将其用在自己的数字化教学场景中。引人入胜的沉浸式体验，吸引了不同年龄段的学生不断尝试和自我完善，通过解决「实际问题」的过程学习经验和方法：<br />· 新颖的「学习方式」更能吸引学生注意力，大家可以在同一个虚拟空间中更自如地合作，挥洒创意。<br />· 通过寓教于乐的方式培养学生沟通交流、配合协作、批判性思维、创新精神，以及计算机化的思维方式。<br />· 完善的引导和定制功能，教师可以根据教学需求灵活定制一个供学生探索的世界，并能通过各种Mod和扩展获得更丰富的功能<br />· 根据研究，通过这种模拟方式的游戏和学习，学生的平均成绩提高了12%。</p>',
			'regurl':'https://msgovsolution.anruichina.com/edu/Home/Video',
			'gallery': ['']
		},
		{ 
			'name':'MSX // Data Insights',
			'contenttype': 'article',
			'logo':'di-236-144.jpg',
			'banner':'di-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Nov 16, 2016',
			'eventtime':'下午2:30-下午6:00',
			'expirydate':'2016-11-16T14:30:00+08:00',
			'location':'Microsoft Experience Center',
			'eventfor': ['中小型企业经营者', 'IT专业人员','业务管理者'],
			'eventtype': ['研讨会及会议'],
			'category': ['线下会议'],
			'product': ['Power BI'],
			'description': '<p>When you make better sense of your data, your insights can transform your business. At MSX // Data Insights, we want to help you bring your data to life and take the next step in your data journey toward intelligent action. That can mean framing or reframing the questions you\'re starting with, or just using your data in new ways to drive more impactful business outcomes.</p><p>MSX // Data Insights is a technology showcase event organized by Microsoft Hong Kong featuring the future of intelligent systems with data insights solutions. This event will also feature Microsoft\'s Smart City solutions, demonstrating how Microsoft is empowering cities to transform their operations and citizen services and foster economic development with a people-first approach.</p>',
			'regurl':'#',
			'gallery': [{'s':'img1_s.jpg', 'l':'img1_l.jpg'}, {'s':'img2_s.jpg', 'l':'img2_l.jpg'}, {'s':'img3_s.jpg', 'l':'img3_l.jpg'}]
		}
		,{ 
			'name':'【Tech Forum】Using Skype for Business as Your Unified Communication Tool',
			'contenttype': 'article',
			'logo':'tech-training-236-144.jpg',
			'banner':'tech-training-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Nov 8, 2016',
			'eventtime':'下午6:30-下午8:30',
			'expirydate':'2016-11-08T18:30:00+08:00',
			'location':'The Hub, Wan Chai',
			'eventfor': ['IT专业人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Skype'],
			'description': '<p>Connect with your team members, wherever they are, using the Office applications they are happy to use every day. With Skype for Business you can simplify your infrastructure with one platform for calling, conferencing, video and sharing. With our mobile apps across Windows, iOS and Android, you can connect them, or bring remote participants into meeting spaces of all sizes with Skype for Business Room Systems and Surface Hub. It’s like working together as if you are all in one room, wherever you are.</p><p>From collaborative team sessions to large broadcasts or dialing into a conference using your phone, Skype for Business addresses all your meeting needs. In addition, Skype for Business makes it easy to make, receive and transfer business calls in the office, at home or on the road using phone, PC and mobile. Increase agility and consolidate management with voice services in Office 365. </p>',
			'regurl':'#',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Forum】Bot & AI of Microsoft Cognitive Service',
			'contenttype': 'article',
			'logo':'bot-236-144.jpg',
			'banner':'bot-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Nov 9, 2016',
			'eventtime':'下午6:00-下午9:00',
			'expirydate':'2016-11-09T18:00:00+08:00',
			'location':'Feva Works IT Education Centre, Wan Chai',
			'eventfor': ['IT专业人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Microsoft Azure'],
			'description': '<p>Following on the overwhelming response from the previous Tech Forum on Bot building, we have prepared a follow up Tech Training for you.</p><p>Build and connect intelligent bots to interact with your users naturally wherever they are, from text/sms to Skype, Slack, Office 365 mail and other popular services. The Framework provides developers with a developer portal and SDK to build Bots, a Bot Connector service to connect to social channels such as Twitter and Slack, and a Bot Directory to discover and use existing bots.</p><p>Bots are as vital a way for users to interact with a service or application as is a web site or a mobile experience. Developers writing bots all face the same problems: bots require basic I/O; they must have language and dialog skills; and they must connect to users.</p><p>The Bot Framework provides tools to easily solve these problems, and more, for developers, e.g. automatic translation to more than 30 languages, user and conversation state management, debugging tools, an embeddable web chat control and a way for users to discover, try and add bots to the conversation experiences they love.</p>',
			'regurl':'#',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Forum】Windows Server 2016 Overview',
			'contenttype': 'article',
			'logo':'ws-236-144.jpg',
			'banner':'ws-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Nov 9, 2016',
			'eventtime':'下午7:00-下午10:00',
			'expirydate':'2016-11-09T19:00:00+08:00',
			'location':'The Hub, Wan Chai',
			'eventfor': ['IT专业人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Server and Management'],
			'description': 'N/A',
			'regurl':'#',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Forum】Introducing Layers of Security in Windows Server 2016',
			'contenttype': 'article',
			'logo':'ws-236-144.jpg',
			'banner':'ws-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Nov 15, 2016',
			'eventtime':'下午6:30-下午9:30',
			'expirydate':'2016-11-15T18:30:00+08:00',
			'location':'The Hub, Wan Chai',
			'eventfor': ['IT专业人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Server and Management'],
			'description': '<p>Evolving cyber threats have made it harder than ever for IT to secure their applications and data. Attackers are getting more sophisticated, often using compromised, highly privileged admin credentials to control access.</p><p>Windows Server 2016 includes built-in breach resistance mechanisms to thwart attacks on your systems and help meet compliance goals. Even if someone finds a way into your environment, the layers of security built into every Windows Server 2016 system limit the damage they can cause.</p><p>Microsoft Windows Server 2016 wants to protect 3 things.</p><p>1. Protect privileged identity.<br />2. Protect the OS no matter where it is running on any host<br />3. Protect the virtual machines from virtualized fabrics.</p><p>Dive deep into Windows Server 2016 with Built-in Security and understand how Windows Server 2016 can safeguard businesses from cyber attacks with layers of built-in protection.</p>',
			'regurl':'#',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Training】Using Skype for Business as Your Unified Communication Tool',
			'contenttype': 'article',
			'logo':'tech-training-236-144.jpg',
			'banner':'tech-training-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Nov 16, 2016',
			'eventtime':'下午2:00-下午5:00',
			'expirydate':'2016-11-16T14:00:00+08:00',
			'location':'Infocan Centre, Kwun Tong',
			'eventfor': ['IT专业人员','开发人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Skype'],
			'description': '<p>At the heart of great teams is great communication</p><p>Connect with your team members, wherever they are, using the Office applications they are happy to use every day. With Skype for Business you can simplify your infrastructure with one platform for calling, conferencing, video and sharing. With our mobile apps across Windows, iOS and Android, you can connect them, or bring remote participants into meeting spaces of all sizes with Skype for Business Room Systems and Surface Hub. It’s like working together as if you are all in one room, wherever you are.</p><p>From collaborative team sessions to large broadcasts or dialing into a conference using your phone, Skype for Business addresses all your meeting needs. In addition, Skype for Business makes it easy to make, receive and transfer business calls in the office, at home or on the road using phone, PC and mobile. Increase agility and consolidate management with voice services in Office 365.</p><p>Get Training on:<br />Skype across devices<br />Complete meeting solutions<br />Modern voice with Cloud PBX<br />Security, control and compliance</p>',
			'regurl':'#',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Forum】Unveil the Security and Compliance Features of Office 365',
			'contenttype': 'article',
			'logo':'tech-training-236-144.jpg',
			'banner':'tech-training-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Nov 22, 2016',
			'eventtime':'下午6:30-下午9:30',
			'expirydate':'2016-11-22T18:30:00+08:00',
			'location':'The Hub, Wan Chai',
			'eventfor': ['IT专业人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Office'],
			'description': '<p>We live in an ever-changing world where business needs and your employees’ needs for productivity challenge the security of your organization’s data. Paired with an evolving threat landscape, your organization must work harder than ever to stay ahead of the threats of tomorrow. Keeping your data secured is pivotal to your company’s success. </p><p>Office 365 is the most complete and secure productivity service for the digital workplace.  Come join us and explore the Security and Compliance features of Office 365.  You can be confident that your data is more secure from threats and compliant with industry regulations.</p><p>From the forum, we will explore securities features of Office 365 including:<br />Help keep your email safe<br />Simplified management<br />Designed for compliance<br />Protect all devices<br />Dive deep into the built-in security and compliance features within Office 365 solutions. Understand how Office 365 helps you to protect your organization while at the same time enabling your workforce to work more efficiently and collaborate more easily.</p>',
			'regurl':'#',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Training】Introducing Layers of Security in Windows Server 2016',
			'contenttype': 'article',
			'logo':'ws-236-144.jpg',
			'banner':'ws-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Nov 23, 2016',
			'eventtime':'上午9:30-下午5:00',
			'expirydate':'2016-11-23T09:30:00+08:00',
			'location':'Feva Works IT Education Centre, Wan Chai',
			'eventfor': ['IT专业人员','开发人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Server and Management'],
			'description': '<p>Evolving cyber threats have made it harder than ever for IT to secure their applications and data. Attackers are getting more sophisticated, often using compromised, highly privileged admin credentials to control access.<p>Windows Server 2016 includes built-in breach resistance mechanisms to thwart attacks on your systems and help meet compliance goals. Even if someone finds a way into your environment, the layers of security built into every Windows Server 2016 system limit the damage they can cause.<p>Get hands-on experience to understand how Windows Server 2016 can safeguard businesses from cyber attacks with layers of built-in protection.<br />Course Outline:<br />Security and Authentication<br />Just Enough Administration / Just in Time Administration<br />Shielded VMs<br />Host Guardian Service<br />Remote Desktop Services<br />RDS – Graphics Improvement</p>',
			'regurl':'#',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Training】Using Skype for Business as Your Unified Communication Tool',
			'contenttype': 'article',
			'logo':'tech-training-236-144.jpg',
			'banner':'tech-training-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Nov 23, 2016',
			'eventtime':'下午2:00-下午5:00',
			'expirydate':'2016-11-23T14:00:00+08:00',
			'location':'Infocan Centre, Kwun Tong',
			'eventfor': ['IT专业人员','开发人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Skype'],
			'description': '<p>At the heart of great teams is great communication</p><p>Connect with your team members, wherever they are, using the Office applications they are happy to use every day. With Skype for Business you can simplify your infrastructure with one platform for calling, conferencing, video and sharing. With our mobile apps across Windows, iOS and Android, you can connect them, or bring remote participants into meeting spaces of all sizes with Skype for Business Room Systems and Surface Hub. It’s like working together as if you are all in one room, wherever you are.</p><p>From collaborative team sessions to large broadcasts or dialing into a conference using your phone, Skype for Business addresses all your meeting needs. In addition, Skype for Business makes it easy to make, receive and transfer business calls in the office, at home or on the road using phone, PC and mobile. Increase agility and consolidate management with voice services in Office 365.</p><p>Get Training on:<br />Skype across devices<br />Complete meeting solutions<br />Modern voice with Cloud PBX<br />Security, control and compliance</p>',
			'regurl':'#',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Forum】Develop Your Machine Learning Model-Future Predictions',
			'contenttype': 'article',
			'logo':'bot-236-144.jpg',
			'banner':'bot-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Nov 23, 2016',
			'eventtime':'下午6:30-下午9:30',
			'expirydate':'2016-11-23T18:30:00+08:00',
			'location':'The Hub, Wan Chai',
			'eventfor': ['IT专业人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Microsoft Azure'],
			'description': '<p>Machine learning is a technique of data science that helps computers learn from existing data in order to forecast future behaviors, outcomes and trends. </p><p>These forecasts or predictions from machine learning can make apps and devices smarter. When you shop online, machine learning helps recommend other products you might like, based on what you\'ve purchased. When your credit card is swiped, machine learning compares the transaction to a database of transactions and helps detect fraud. When your robot vacuum cleaner vacuums a room, machine learning helps it decide whether the job is done.</p><p>Azure Machine Learning is a cloud-based service for building machine-learning models using a drag-and-drop user interface. With Azure Machine Learning, you can perform sophisticated predictive analytics from data sets large or small, using an assortment of included algorithms, or using code algorithms of your own in R and Python. </p><p>Join our Tech Forum for an exploration of Azure Machine Learning, and see how machine can perform sophisticated predictive analytics. Get a fast start on Azure Machine Learning with this forum.<br />Agenda <br />What is machine learning?<br />Introduction to Azure ML Studio<br />Demonstration<br />Designing a Predictive Analytics Solution with Machine Learning Studio</p>',
			'regurl':'#',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Forum】New Generation of Enterprise DR and Backup in Windows Server 2016',
			'contenttype': 'article',
			'logo':'ws-236-144.jpg',
			'banner':'ws-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Nov 29, 2016',
			'eventtime':'下午6:30-下午9:30',
			'expirydate':'2016-11-29T18:30:00+08:00',
			'location':'The Hub, Wan Chai',
			'eventfor': ['IT专业人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Server and Management'],
			'description': '<p>Datacenter operations seem to earn more scrutiny than budget these days. New applications can stretch the operational fabric and create infrastructure backlogs that can slow down business. IT organizations are expected to do more with less, but an aging infrastructure with little automation becomes a hindrance to moving forward.<br />Software-defined storage capabilities in Windows Server 2016, such as Storage Spaces Direct, Storage Replica, Quality of Service and data deduplication, use policies and automation to increase datacenter efficiency and reduce storage management costs.<br />From the forum, you will learn; <br />How to drive efficiency and get ready for cloud with a software-defined datacenter with Windows Server 2016 and Azure Business Continuity<br />Highlights of the new Software-defined Datacenter capabilities across Compute, Storage and Network</p>',
			'regurl':'#',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Training】Unveil the Security and Compliance Features of Office 365',
			'contenttype': 'article',
			'logo':'tech-training-236-144.jpg',
			'banner':'tech-training-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Nov 30, 2016',
			'eventtime':'上午9:30-下午5:00',
			'expirydate':'2016-11-30T09:30:00+08:00',
			'location':'Infocan Centre, Kwun Tong',
			'eventfor': ['IT专业人员','开发人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Office'],
			'description': '<p>We live in an ever-changing world where business needs and your employees’ needs for productivity challenge the security of your organization’s data. Paired with an evolving threat landscape, your organization must work harder than ever to stay ahead of the threats of tomorrow. Keeping your data secured is pivotal to your company’s success.</p><p>Office 365 is the most complete and secure productivity service for the digital workplace.  Come join us and explore the Security and Compliance features of Office 365.  You can be confident that your data is more secure from threats and compliant with industry regulations.</p><p>From the forum, we will explore securities features of Office 365 including:  <br/>Help keep your email safe<br/>Simplified management<br/>Designed for compliance<br/>Protect all devices</p><p>Dive deep into the built-in security and compliance features within Office 365 solutions. Understand how Office 365 helps you to protect your organization while at the same time enabling your workforce to work more efficiently and collaborate more easily.</p>',
			'regurl':'#',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Forum】Powerful Visualized Analytics for both Business Insight and Personal Productivity ',
			'contenttype': 'article',
			'logo':'tech-training-236-144.jpg',
			'banner':'tech-training-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Dec 6, 2016',
			'eventtime':'下午6:30-下午9:30',
			'expirydate':'2016-12-06T18:30:00+08:00',
			'location':'The Hub, Wan Chai',
			'eventfor': ['IT专业人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Power BI'],
			'description': '<p>Are you still figuring out how you can make better use of all the data that you have, from different systems, and turn this into useful business insight that is easy to consume and understand without the need to know the data structure? Are you looking for a solution that can retrieve and consolidate all the data from diverse systems, and enable you to make business decisions in a timely manner?</p><p>Join this technical forum to understand the full capabilities of our Power BI solution, with powerful visualized analytics that give you business insight and help you to increase your productivity with detailed information on how you are spending your time with your counterparts.</p>',
			'regurl':'#',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Training】Unveil the Security and Compliance Features of Office 365',
			'contenttype': 'article',
			'logo':'tech-training-236-144.jpg',
			'banner':'tech-training-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Dec 7, 2016',
			'eventtime':'上午9:30-下午5:00',
			'expirydate':'2016-12-07T09:30:00+08:00',
			'location':'Infocan Centre, Kwun Tong',
			'eventfor': ['IT专业人员','开发人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Office'],
			'description': '<p>We live in an ever-changing world where business needs and your employees’ needs for productivity challenge the security of your organization’s data. Paired with an evolving threat landscape, your organization must work harder than ever to stay ahead of the threats of tomorrow. Keeping your data secured is pivotal to your company’s success.</p><p>Office 365 is the most complete and secure productivity service for the digital workplace.  Come join us and explore the Security and Compliance features of Office 365.  You can be confident that your data is more secure from threats and compliant with industry regulations.</p><p>From the forum, we will explore securities features of Office 365 including:  <br/>Help keep your email safe<br/>Simplified management<br/>Designed for compliance<br/>Protect all devices</p><p>Dive deep into the built-in security and compliance features within Office 365 solutions. Understand how Office 365 helps you to protect your organization while at the same time enabling your workforce to work more efficiently and collaborate more easily.</p>',
			'regurl':'#',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Training】Bot & AI of Microsoft Cognitive Service',
			'contenttype': 'article',
			'logo':'bot-236-144.jpg',
			'banner':'bot-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Dec 7, 2016',
			'eventtime':'下午6:00-下午9:00',
			'expirydate':'2016-12-07T18:00:00+08:00',
			'location':'Feva Works IT Education Centre, Wan Chai',
			'eventfor': ['IT专业人员','开发人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Microsoft Azure'],
			'description': '<p>Following on the overwhelming response from the previous Tech Forum on Bot Building, we have prepared a follow up Tech Training session for you.</p><p>Build and connect intelligent bots to interact with your users naturally wherever they are, from text/sms to Skype, Slack, Office 365 mail and other popular services. The Framework provides developers with a developer portal and SDK to build bots, a Bot Connector service to connect to social channels such as Twitter and Slack, and a Bot Directory to discover and use existing bots.</p><p>Bots are as vital a way for users to interact with a service or application as is a web site or a mobile experience. Developers writing bots all face the same problems: bots require basic I/O; they must have language and dialog skills; and they must connect to users.</p><p>The Bot Framework provides tools to easily solve these problems, and more, for developers, e.g. automatic translation to more than 30 languages, user and conversation state management, debugging tools, an embeddable web chat control and a way for users to discover, try and add bots to the conversation experiences they love.</p>',
			'regurl':'#',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Training】Powerful Visualized Analytics for Both Business Insight and Personal Productivity ',
			'contenttype': 'article',
			'logo':'tech-training-236-144.jpg',
			'banner':'tech-training-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Dec 13, 2016',
			'eventtime':'上午9:30-下午5:00',
			'expirydate':'2016-12-13T09:30:00+08:00',
			'location':'Infocan Centre, Kwun Tong',
			'eventfor': ['IT专业人员','开发人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Power BI'],
			'description': '<p>Are you still figuring out how you can make better use of all the data that you have, from different systems, and turn this into useful business insight that is easy to consume and understand without the need to know the data structure? Are you looking for a solution that can retrieve and consolidate all the data from diverse systems, and enable you to make business decisions in a timely manner? Join this technical forum to understand the full capabilities of our Power BI solution, with powerful visualized analytics that give you business insight and help you to increase your productivity with detailed information on how you are spending your time with your counterparts.</p><p>After this technical training with hands-on experience, you will realize how easy it is to work with data, and how everyone can be a data scientist.</p>',
			'regurl':'#',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Forum】Windows Server 2016 - Innovative Application Development with Container and Docker',
			'contenttype': 'article',
			'logo':'ws-236-144.jpg',
			'banner':'ws-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Dec 13, 2016',
			'eventtime':'下午6:30-下午9:30',
			'expirydate':'2016-12-13T18:30:00+08:00',
			'location':'The Hub, Wan Chai',
			'eventfor': ['IT专业人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Server and Management'],
			'description': '<p>The cloud enables businesses to innovate quickly and deliver faster time-to value with cloud-native applications and microservices architecture. But most businesses are grappling with how to manage and update thousands of existing applications while planning how to move to this new world. What is needed is a solution that helps you invigorate existing applications and create new, cloud-native applications. Windows Server 2016 can do both.<br />Attend the forum to learn how to accelerate your business agility with apps built on Windows Server 2016 and Azure.</p>',
			'regurl':'#',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Training】New Generation of Enterprise DR and Backup in Windows Server 2016',
			'contenttype': 'article',
			'logo':'ws-236-144.jpg',
			'banner':'ws-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Dec 14, 2016',
			'eventtime':'上午9:30-下午5:00',
			'expirydate':'2016-12-14T09:30:00+08:00',
			'location':'Feva Works IT Education Centre, Wan Chai',
			'eventfor': ['IT专业人员','开发人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Server and Management'],
			'description': '<p>Datacenter operations seem to earn more scrutiny than budget these days. New applications can stretch the operational fabric and create infrastructure backlogs that can slow down business. IT organizations are expected to do more with less, but an aging infrastructure with little automation becomes a hindrance to moving forward.<br />Software-defined storage capabilities in Windows Server 2016, such as Storage Spaces Direct, Storage Replica, Quality of Service and data deduplication, use policies and automation to increase datacenter efficiency and reduce storage management costs.</p>',
			'regurl':'#',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Forum】Producing Broadcast Meeting and External Dialing ',
			'contenttype': 'article',
			'logo':'tech-training-236-144.jpg',
			'banner':'tech-training-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Dec 14, 2016',
			'eventtime':'下午6:30-下午9:30',
			'expirydate':'2016-12-14T18:30:00+08:00',
			'location':'The Hub, Wan Chai',
			'eventfor': ['IT专业人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': [''],
			'description': '<p>In this modern age, there is an increasing need for individuals to complete complex tasks by working together with their co-workers as a group. More and more, they have to communicate with different team members in their office, or with counterparts overseas, to collaborate efficiently and effectively to get their task done. How do your phone systems, email systems, instant messages, web conference systems and broadcast meetings work? Do they function seamlessly together or sit in different silos?</p><p>Join this technical forum to learn how you can leverage on a single Microsoft Unified Communication platform to fulfill all communication needs across departments and regions.</p>',
			'regurl':'#',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Forum】Bigger than the Big Data: Getting Insights with Data Analytics',
			'contenttype': 'article',
			'logo':'tech-training-2-236-144.jpg',
			'banner':'tech-training-2-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Dec 15, 2016',
			'eventtime':'下午6:30-下午9:30',
			'expirydate':'2016-12-15T18:30:00+08:00',
			'location':'The Hub, Wan Chai',
			'eventfor': ['IT专业人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': [''],
			'description': '<p>There is a huge amount of data generated each and every day, driven by the increased use of mobile applications, sensors and multiple mainstream social media platforms. With more tools available for streaming and analyzing the data in either a structured or unstructured way, more advanced business use cases are ready to be generated in the coming decade. </p><p>In this Tech Forum, you will learn how to capture their data from different sources, then store and manage the data in the right storage environment. Towards a more advanced level, the forum will cover how Machine Learning models can be chosen and implemented based on different scenarios. </p><p>The speakers will also demonstrate how R and Python can help to implement Machine Learning solutions to make predictions. A showcase of E-Commerce and Financial Services solutions will bring you insights on how to improve your business by capturing the Big Data trend.</p>',
			'regurl':'#',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Forum】Hybrid Cloud Management and Monitoring with System Center 2016 and Azure',
			'contenttype': 'article',
			'logo':'ws-236-144.jpg',
			'banner':'ws-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Dec 20, 2016',
			'eventtime':'下午6:30-下午9:30',
			'expirydate':'2016-12-20T18:30:00+08:00',
			'location':'The Hub, Wan Chai',
			'eventfor': ['IT专业人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Microsoft Azure'],
			'description': '<p>Managing the hybrid cloud presents new challenges, and companies often end up with multiple tools scattered over multiple locations. This makes it difficult to gain actionable insights, as well as to troubleshoot and remediate quickly in a unified manner.</p><p>The new System Center 2016 and Operation Management Suite (OMS) is designed to help you achieve a simple and unified experience, gain immediate insight, and troubleshoot quickly and auto-remediate – no matter what type of resources you have or where they are located.<br/>From this forum, you will learn how to:<br/>Gain visibility and troubleshoot issues faster for your Hybrid IT Infrastructure<br/>Get a unified view across multiple data sources such as Linux, Windows, AWS and Azure<br/>Rapidly develop actionable insights using built-in intelligence<br/>Separate the signal from the noise with simple, powerful management tools<br/>Identify the root cause of problems in your IT environment through powerful search capabilities<br/>Automate remediation based on alerts from aggregated data</p>',
			'regurl':'#',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Training】Azure 101 Technical Hands-on Training',
			'contenttype': 'article',
			'logo':'azure-236-144.jpg',
			'banner':'azure-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Jan 3, 2017',
			'eventtime':'上午9:30-下午5:00',
			'expirydate':'2017-01-03T09:30:00+08:00',
			'location':'Infocan Centre, Kwun Tong',
			'eventfor': ['IT专业人员','开发人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Microsoft Azure'],
			'description': '<p>Microsoft Azure is one of the leading public cloud platforms in the world and its momentum keeps growing tremendously. With the ongoing development of Azure cloud services, the Azure platform is best for rapid business growth to help scale our customers’ businesses.</p><p>This training starts with an introduction to Microsoft Azure Virtual Machines, Storage, and Virtual Networks, and Infrastructure Services.  It is an opportunity to gain foundational knowledge needed to run new workloads in Microsoft Azure or migrate existing workloads from on-premises environments.</p><p>In this full-day hands on training, you will learn:<br/>An introduction to Microsoft Azure cloud platform<br/>Provision virtual machines (VM) in Azure<br/>Concepts of storage in Azure<br/>Perform backup and site recovery<br/>Monitor Azure VM using single panel or with PowerShell<br/>Extend your existing on-premises Active Directory to Azure AD and achieve more with the cloud<br/>Perform management and monitoring tasks in Azure</p>',
			'regurl':'https://aka.ms/bmjryi',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Training】Powerful Visualized Analytics for both Business Insight and Personal Productivity',
			'contenttype': 'article',
			'logo':'tech-training-2-236-144.jpg',
			'banner':'tech-training-2-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Jan 4, 2017',
			'eventtime':'上午9:30-下午5:00',
			'expirydate':'2017-01-04T09:30:00+08:00',
			'location':'Infocan Centre, Kwun Tong',
			'eventfor': ['IT专业人员','开发人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Power BI'],
			'description': '<p>Are you still figuring out how you can make better use of all the data that you have, from different systems, and turn this into useful business insight that is easy to consume and understand without the need to know the data structure? Are you looking for a solution that can retrieve and consolidate all the data from diverse systems, and enable you to make business decisions in a timely manner? Join this technical forum to understand the full capabilities of our Power BI solution, with powerful visualized analytics that give you business insight and help you to increase your productivity with detailed information on how you are spending your time with your counterparts.</p><p>After this technical training with hands-on experience, you will realize how easy it is to work with data, and how everyone can be a data scientist.</p>',
			'regurl':'https://aka.ms/gc303i',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Training】SQL Technical 101 Hands-on Training',
			'contenttype': 'article',
			'logo':'tech-training-2-236-144.jpg',
			'banner':'tech-training-2-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Jan 9, 2017',
			'eventtime':'上午9:30-下午5:00',
			'expirydate':'2017-01-09T09:30:00+08:00',
			'location':'Infocan Centre, Kwun Tong',
			'eventfor': ['IT专业人员','开发人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Server and Management'],
			'description': '<p>The foundation of Microsoft’s comprehensive data platform, SQL Server delivers breakthrough performance for mission-critical applications, using in-memory technologies, faster insights from any data to any user in familiar tools like Excel, and a resilient platform for building, deploying, and managing solutions that span on-premises and cloud. In this workshop, you can get hands-on instruction and experience of implementing Microsoft SQL Server 2016 and Power BI.<br/>SQL Server 2016 Overview<br/>What’s New in Database Engine<br/>What’s New in Analysis Services and Business Intelligence<br/>Mission Critical:  In-Memory Technologies<br/>In-Memory OLTP<br/>In-Memory for Database Developers<br/>In-Memory for Data warehouse<br/>Business Intelligence:  Power BI<br/>Power Pivot<br/>Power Query<br/>Power View<br/>Power Map<br/>Power Q&A<br/>Upgrading to SQL Server 2016<br/>Requirements for Installing SQL Server 2016<br/>Upgrading from Previous Versions<br/>SQL Server 2016 Cloud Integration</p>',
			'regurl':'https://aka.ms/bmjryi',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Forum】What Components of Office 365 to Use and When?',
			'contenttype': 'article',
			'logo':'tech-training-236-144.jpg',
			'banner':'tech-training-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Jan 10, 2017',
			'eventtime':'下午6:30-下午9:30',
			'expirydate':'2017-01-10T18:30:00+08:00',
			'location':'The Hub, Wan Chai',
			'eventfor': ['IT专业人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Office'],
			'description': '<p>There are a lot of great features within Office 365, including Groups, Yammer, Skype, OneDrive, SharePoint, and now newly-announced Teams will be joining the camp.  You may be using some of them already.  However, have you ever thought about what tools you should use for a particular purpose?  <br />Come join this technical forum to learn how best to use these versatile and powerful Office 365 features.</p>',
			'regurl':'https://aka.ms/nyie8f',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Forum】Building a Bot on Cloud that Brings You more Opportunities*',
			'contenttype': 'article',
			'logo':'bot-236-144.jpg',
			'banner':'bot-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Jan 12, 2017',
			'eventtime':'下午6:30-下午9:30',
			'expirydate':'2017-01-12T18:30:00+08:00',
			'location':'The Hub, Wan Chai',
			'eventfor': ['IT专业人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Microsoft Azure'],
			'description': '<p>Stemming from traditional app services, bots now a hot topic related to innovations. Bots can help to enhance different types of services that you currently provide to your customers, and they can save operating costs while increasing the efficiency and standardization of quality of the services to be provided.</p><p>Microsoft is one of the leaders in the IT industry, not only developing its own bots, but also providing a Bot Framework for the developer community to build different bots using technologies available on cloud, such as Machine Learning.</p><p>This seminar covers how Microsoft’s cloud can empower individuals and companies to achieve their business/development objectives, and especially how a bot can be built in the cloud to give it high accessibility for both your team and your customers.</p><p>Industrial advice will also be provided on how you can be a professional in relation to the cloud.</p>',
			'regurl':'https://aka.ms/nk5pov',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Training】Producing Broadcast Meeting and External Dialing',
			'contenttype': 'article',
			'logo':'tech-training-236-144.jpg',
			'banner':'tech-training-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Jan 12, 2017',
			'eventtime':'上午9:30-下午5:00',
			'expirydate':'2017-01-12T09:30:00+08:00',
			'location':'Infocan Centre, Kwun Tong',
			'eventfor': ['IT专业人员','开发人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': [''],
			'description': '<p>In this modern age, there is an increasing need for individuals to complete complex tasks by working together with their co-workers as a group. More and more, they have to communicate with different team members in their office, or with counterparts overseas, to collaborate efficiently and effectively to get their task done. How do your phone systems, email systems, instant messages, web conference systems and broadcast meetings work? Do they function seamlessly together or sit in different silos?</p><p>Join this technical forum to learn how you can leverage on a single Microsoft Unified Communication platform to fulfill all communication needs across departments and regions.</p>',
			'regurl':'https://aka.ms/ew61wf',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Forum】Experience Open Source Linux on Microsoft Azure Step-by-Step',
			'contenttype': 'article',
			'logo':'azure-236-144.jpg',
			'banner':'azure-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Jan 16, 2017',
			'eventtime':'下午6:30-下午9:30',
			'expirydate':'2017-01-16T18:30:00+08:00',
			'location':'The Hub, Wan Chai',
			'eventfor': ['IT专业人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Microsoft Azure'],
			'description': '<p>In many of today’s environments, customers need to use multiple tools to monitor both their Microsoft Windows Server and Linux workloads and applications. The challenge increases when workloads exist across different locations, and even different clouds. </p><p>In this session, we show you how you can deploy your existing Linux workloads on Microsoft Azure step by step and provide an easily way to monitor your Linux applications and infrastructure.</p>',
			'regurl':'https://aka.ms/iija2o',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Training】Producing Broadcast Meeting and External Dialing ',
			'contenttype': 'article',
			'logo':'tech-training-236-144.jpg',
			'banner':'tech-training-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Jan 18, 2017',
			'eventtime':'上午9:30-下午5:00',
			'expirydate':'2017-01-18T09:30:00+08:00',
			'location':'Infocan Centre, Kwun Tong',
			'eventfor': ['IT专业人员','开发人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': [''],
			'description': '<p>In this modern age, there is an increasing need for individuals to complete complex tasks by working together with their co-workers as a group. More and more, they have to communicate with different team members in their office, or with counterparts overseas, to collaborate efficiently and effectively to get their task done. How do your phone systems, email systems, instant messages, web conference systems and broadcast meetings work? Do they function seamlessly together or sit in different silos?</p><p>Join this technical forum to learn how you can leverage on a single Microsoft Unified Communication platform to fulfill all communication needs across departments and regions.</p>',
			'regurl':'https://aka.ms/r2l7j9',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Training】What Components of Office 365 to Use and When?',
			'contenttype': 'article',
			'logo':'tech-training-236-144.jpg',
			'banner':'tech-training-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Jan 19, 2017',
			'eventtime':'上午9:30-下午5:00',
			'expirydate':'2017-01-19T09:30:00+08:00',
			'location':'Infocan Centre, Kwun Tong',
			'eventfor': ['IT专业人员','开发人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Office'],
			'description': '<p>There are a lot of great features within Office 365, including Groups, Yammer, Skype, OneDrive, SharePoint, and now newly-announced Teams will be joining the camp. You may be using some of them already. However, have you ever thought about what tools you should use for a particular purpose? <br />Come join this technical training to learn how best to use these versatile and powerful Office 365 features, and get first-hand experience using those features you may not have previously known existed.</p>',
			'regurl':'https://aka.ms/cnrhmy',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Forum】Introduction to Advanced Analytics and Big Data',
			'contenttype': 'article',
			'logo':'tech-training-2-236-144.jpg',
			'banner':'tech-training-2-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Jan 24, 2017',
			'eventtime':'下午6:30-下午9:30',
			'expirydate':'2017-01-24T18:30:00+08:00',
			'location':'The Hub, Wan Chai',
			'eventfor': ['IT专业人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Power BI'],
			'description': '<p>Enterprises that transform data into intelligent action are outperforming their competitors and will be the businesses of the future. As you know, we’re at the exciting forefront of helping customers create systems of intelligence that can transform the way they do business – from interacting with their own customers and employees to their daily operations and even business models.<br/>In order to fully realize this opportunity, we all need to connect with our customers and partners about the real business problems they are facing in their industries. There is no question that Advanced Analytics (AA) and Big Data, which are at the core of market intelligence, can deliver a huge business impact. But the digital transformation journey can be disruptive and challenging, and crucial to our success is the ability to guide our customers and partners with the right conversations.</p>',
			'regurl':'https://aka.ms/cm0c3p',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Forum】The Most Comprehensive Office Suite, Office 365 E5',
			'contenttype': 'article',
			'logo':'tech-training-236-144.jpg',
			'banner':'tech-training-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Mar 7, 2017',
			'eventtime':'下午6:30-下午9:30',
			'expirydate':'2017-03-07T18:30:00+08:00',
			'location':'The Hub, Wan Chai',
			'eventfor': ['IT专业人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Office'],
			'description': '<p>Microsoft Office 365 E5 is the most comprehensive suite within the Office 365 product family. Features range from productivity capabilities that most people are familiar with, to security features that are much desired by enterprises these days, and to the power of analytics for every Office user.</p><p>Come join us to learn about all these cool features that come with the most comprehensive Office 365 suite ever.</p>',
			'regurl':'https://aka.ms/rq48g0',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Training】What Components of Office 365 to Use and When?',
			'contenttype': 'article',
			'logo':'tech-training-236-144.jpg',
			'banner':'tech-training-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Mar 9, 2017',
			'eventtime':'上午9:00-下午5:00',
			'expirydate':'2017-03-09T09:00:00+08:00',
			'location':'Infocan Centre, Kwun Tong',
			'eventfor': ['IT专业人员','开发人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Office'],
			'description': '<p>There are a lot of great features within Office 365, including Groups, Yammer, Skype, OneDrive, SharePoint, and now newly-announced Teams will be joining the camp. You may be using some of them already. However, have you ever thought about what tools you should use for a particular purpose? </p><p>Come join this technical training to learn how best to use these versatile and powerful Office 365 features, and get first-hand experience using those features you may not have previously known existed.</p>',
			'regurl':'https://aka.ms/pcysld',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Forum】Deploy and Defend Windows Clients from Modern Threats with Windows 10 Security',
			'contenttype': 'article',
			'logo':'tech-training-236-144.jpg',
			'banner':'tech-training-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Mar 13, 2017',
			'eventtime':'下午6:30-下午9:30',
			'expirydate':'2017-03-13T18:30:00+08:00',
			'location':'The Hub, Wan Chai',
			'eventfor': ['IT专业人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Windows'],
			'description': '<p>Windows 10 offers an enormous leap forward when it comes to threat resistance, but that is just the beginning. In this Tech Forum, you will be equipped with an impressive lineup of new Windows 10 capabilities including WDATP and Creators Update, along with deployment knowledge to raise the security bar even further for malware and other online threats.</p>',
			'regurl':'https://aka.ms/r8fjri',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Training】Hands on training for Microsoft SQL R Server',
			'contenttype': 'article',
			'logo':'azure-236-144.jpg',
			'banner':'azure-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Mar 14, 2017',
			'eventtime':'上午9:30-下午5:00',
			'expirydate':'2017-03-14T09:30:00+08:00',
			'location':'Infocan Centre, Kwun Tong',
			'eventfor': ['IT专业人员','开发人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Server and Management'],
			'description': '<p>Supporting a variety of big data statistics, predictive modeling and machine-learning capabilities, R Server supports a full range of analytics, from exploration to analysis to visualization to modeling. It’s fully compatible with R scripts, functions and comprehensive R archive network packages to analyze data at enterprise scale. <br />In this workshop, you will gain hands-on experience with advanced analytics by deploying Predictive Modeling with Azure Machine Learning using open source R languages. You will also learn about architecture design for big data and experience Azure Data Factory and Azure Data Lake.</p> ',
			'regurl':'https://aka.ms/qphkww',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Forum】Identity Driven Security: Protect Your Active Directory (AD) both in the Cloud and On-premises',
			'contenttype': 'article',
			'logo':'azure-236-144.jpg',
			'banner':'azure-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Mar 16, 2017',
			'eventtime':'下午6:30-下午9:30',
			'expirydate':'2017-03-16T18:30:00+08:00',
			'location':'The Hub, Wan Chai',
			'eventfor': ['IT专业人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Microsoft Azure'],
			'description': '<p>Explore how Microsoft Azure AD and Advanced Threat Analytics take secure identity and access management to the next level. These features put the power of conditional access and advanced risk analytics, just-in-time administration and security reviews in your hand to stop cyber criminals from gaining entry to your systems. Azure AD Identity Protection is built on Microsoft\'s global experience in protecting consumer identities. It gains tremendous accuracy as it processes over 13 billion logins a day.<br />In this session, we demonstrate the detection capabilities, real time prevention using conditional access, the end user experiences, just-in-time administration and SIEM/ analytics extensibility.</p>',
			'regurl':'https://aka.ms/d27pkq',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Forum】Introduction of Power BI with Interactive Live Demo',
			'contenttype': 'article',
			'logo':'tech-training-2-236-144.jpg',
			'banner':'tech-training-2-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Mar 21, 2017',
			'eventtime':'下午6:30-下午9:30',
			'expirydate':'2017-03-21T18:30:00+08:00',
			'location':'The Hub, Wan Chai',
			'eventfor': ['IT专业人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Power BI'],
			'description': '<p>Power BI is quickly gaining popularity among professionals in data science as a cloud-based service that helps them easily visualize and share insights from their organizations’ data.</p><p>In this forum, you will learn about Power BI with some interactive live demos that demonstrate how to turn data into business insights. You’ll also learn to create dashboards and share with business users—on the web and on mobile devices.</p>',
			'regurl':'https://aka.ms/qevv28',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Training】The Most Comprehensive Office Suite, Office 365 E5',
			'contenttype': 'article',
			'logo':'tech-training-236-144.jpg',
			'banner':'tech-training-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Mar 23, 2017',
			'eventtime':'上午9:00-下午5:00',
			'expirydate':'2017-03-23T09:00:00+08:00',
			'location':'Infocan Centre, Kwun Tong',
			'eventfor': ['IT专业人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Office'],
			'description': '<p>Microsoft Office 365 E5 is the most comprehensive suite within the Office 365 product family. Features range from productivity capabilities that most people are familiar with, to security features that are much desired by enterprises these days, and to the power of analytics for every Office user.</p><p>Come join this technical training to learn about all these cool features that come with the most comprehensive Office 365 suite ever, and you will see just how easy it is to enable these features offered in Office 365 E5 in no time at all!</p>',
			'regurl':'https://aka.ms/frfzcj',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Forum】Running Your RedHat Solutions on Microsoft Azure',
			'contenttype': 'article',
			'logo':'azure-236-144.jpg',
			'banner':'azure-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Mar 27, 2017',
			'eventtime':'下午6:30-下午9:30',
			'expirydate':'2017-03-27T18:30:00+08:00',
			'location':'The Hub, Wan Chai',
			'eventfor': ['IT专业人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Microsoft Azure'],
			'description': '<p>Join this session and see how you can run your RedHat\'s open source solutions on Microsoft Azure to scale enterprise applications. Take a deep dive into RedHat\'s PaaS solution, learn best practices and see case studies.</p>',
			'regurl':'https://aka.ms/ql9cp3',
			'gallery': ['']
		}
		,{ 
			'name':'【Tech Training】The Most Comprehensive Office Suite, Office 365 E5',
			'contenttype': 'article',
			'logo':'tech-training-236-144.jpg',
			'banner':'tech-training-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Mar 30, 2017',
			'eventtime':'上午9:00-下午5:00',
			'expirydate':'2017-03-30T09:00:00+08:00',
			'location':'Infocan Centre, Kwun Tong',
			'eventfor': ['IT专业人员','开发人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Office'],
			'description': '<p>Microsoft Office 365 E5 is the most comprehensive suite within the Office 365 product family. Features range from productivity capabilities that most people are familiar with, to security features that are much desired by enterprises these days, and to the power of analytics for every Office user. </p><p>Come join this technical training to learn about all these cool features that come with the most comprehensive Office 365 suite ever, and you will see just how easy it is to enable these features offered in Office 365 E5 in no time at all!</p>',
			'regurl':'https://aka.ms/j37swc',
			'gallery': ['']
		}
		,{ 
			'name':'Webinar Series #1 - Top Security Threats Facing Your Business and How Pro-Tech Can Help You Respond',
			'contenttype': 'article',
			'logo':'dmm-1-236-144.jpg',
			'banner':'dmm-1-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Aug 10, 2016',
			'eventtime':'下午3:00-下午4:00',
			'expirydate':'2016-08-10T15:00:00+08:00',
			'location':'',
			'eventfor': ['IT专业人员', '开发人员'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': [''],
			'description': '<p>Do you know the top security threats facing your business? <br/>Do you want to be able to detect hackers inside your organization? <br/>Identify and protect confidential information and keep them from inappropriate sharing? <br/>Ensure only your employees have access to your corporate email, apps and data? <br/>Join us in this webinar to find out the answers and how you can protect your business and respond to security threats effectively.</p><p>Take action to protect your business from cybersecurity threats. Claim a 1-time special consultancy offer by attending this webinar. What you will get:<br/>• Detailed steps of how to apply the security protection measures you just learned <br/>• Consultant to tailor fit those security practice into your environment <br/>Written report to document your next steps: the what and the how</p>',
			'regurl':'https://aka.ms/moqb0i',
			'gallery': ['']
		}
		,{ 
			'name':'Webinar Series #2 - Your Cloud Document Vault - Access Anywhere, Anytime Assured',
			'contenttype': 'article',
			'logo':'azure-236-144.jpg',
			'banner':'azure-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Aug 18, 2016',
			'eventtime':'下午3:00-下午4:00',
			'expirydate':'2016-08-18T15:00:00+08:00',
			'location':'',
			'eventfor': ['IT专业人员'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Azure'],
			'description': '<p>Do you have large batch of documents that you need to store securely online with sharing access to different approved parties? Tune in to this webcast featuring iNAS\' solution - your secure cloud document vault, accessible anywhere and anytime. Take advantage of the 30-days free trial for iNAS\' backup solutions and Microsoft\'s ModernBiz package designed to drive your business success.</p>',
			'regurl':'https://aka.ms/kaox1r',
			'gallery': ['']
		}
		,{ 
			'name':'Webinar Series #3 - Retailers\' Guide to Improving Customer Stickiness',
			'contenttype': 'article',
			'logo':'dmm3-236-144.jpg',
			'banner':'dmm3-630-236.jpg',
			'youtubeurl': '',
			'eventdate':'Sep 7, 2016',
			'eventtime':'下午3:00-下午4:00',
			'expirydate':'2016-09-07T15:00:00+08:00',
			'location':'',
			'eventfor': ['IT专业人员'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Dynamics','Power BI'],
			'description': '<p>86% of consumers say they are willing to pay more for better customer experiences, and 65% of them will switch to competitors if they have negative experience with a company.<br/>In this webinar, Tom Mok, Technical Director of CoreMinder will outline CoreLoyalty, a comprehensive Customer Loyalty solution tailored for SMB retailers which allows:<br/>• E-membership and E-transactions on mobile devices <br/>• Omni-channel access to sales and loyalty programs <br/>• End-to-end opportunity management with Sales and Customer Service teams<br/>• Win and keep customers happy through CRM data insight</p>',
			'regurl':'https://aka.ms/xfixgq',
			'gallery': ['']
		}
		,{ 
			'name':'Webinar Series #4 - Marketer\'s Guide to Chatbots for Customer Service Transformation',
			'contenttype': 'article',
			'logo':'bot-236-144.jpg',
			'banner':'bot-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Sep 22, 2016',
			'eventtime':'下午3:00-下午4:00',
			'expirydate':'2016-09-22T15:00:00+08:00',
			'location':'',
			'eventfor': ['IT专业人员'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Azure'],
			'description': '<p>Chatbots powered by artificial intelligence (AI), are transforming the way companies interact and do business with their customers. Companies can leverage chatbots in 3 primary ways: to deliver content to customers, for customer service and to deliver productivity or transactional services.</p><p>During the webinar, you will learn:<br/>• How you can achieve "always-on" customer engagement.<br/>• How to leverage on chatbots to increase sales.<br/>• How to optimize operations 24x7 without human resource. <br/>• How you can implement a Facebook Messenger chatbot for free.</p>',
			'regurl':'https://aka.ms/p7npyi',
			'gallery': ['']
		}
		,{ 
			'name':'Webinar Series #5 - How to Digitize Your Campus',
			'contenttype': 'article',
			'logo':'dmm5-236-144.jpg',
			'banner':'dmm5-630-236.jpg',
			'youtubeurl': '',
			'eventdate':'Oct 5, 2016',
			'eventtime':'下午3:00-下午4:00',
			'expirydate':'2016-10-05T15:00:00+08:00',
			'location':'',
			'eventfor': ['IT专业人员', '教育工作者'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Dynamics'],
			'description': '<p>The student is also a customer! The key to many challenges facing modern education institutions is that they now need to be far more astute and conscious in building and managing relations with their students. We believe that students, like any other customer, want to have a better experience when they are engaging with their institution of choice. For example, we hear that students would like the institution to communicate with them on their own terms – and email is not always the best method – communications through social media, SMS messages, Skype calls and interviews could be far more preferable and efficient.</p><p>Applying to an Education institution and embarking on a journey through that institution is usually a complex process. The student needs to be guided through the process, and they increasingly look to the institution to make this as simple as possible.</p><p>In this webinar, Crimson will demonstrate the benefits of using the Student Life Cycle Management system, to optimize the parent/student experience in interacting with the school, while at the same time, increase staff productivity and co-operation. Crimson’s solution can also integrate with various school systems or databases, including integration with the current website to provide application portal or parent/student service portal.</p>',
			'regurl':'https://aka.ms/e7v8k5',
			'gallery': ['']
		}
		,{ 
			'name':'Webinar Series #6 - Your desktop on the go : Work anywhere on any device',
			'contenttype': 'article',
			'logo':'dmm-6-236-144.jpg',
			'banner':'dmm-6-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Oct 12, 2016',
			'eventtime':'下午3:00-下午4:00',
			'expirydate':'2016-10-12T15:00:00+08:00',
			'location':'',
			'eventfor': ['IT专业人员'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Azure'],
			'description': '<p>Hardware investment and software license agreements take up a good portion of working capital for businesses of any size. These investments can sometimes make it difficult to accommodate your growing business needs or weather unforeseen market disruptions.</p><p>In this webinar, you will be introduced to solutions to help your business reduce IT spending inefficiencies, increase employee productivity and create flexible IT infrastructure to meet your changing business needs.</p><p>Topics covered in this webinar will include 24/7 remote desktop through any device, integration & migration, and the technology that makes all these services possible.</p>',
			'regurl':'https://aka.ms/n0epli',
			'gallery': ['']
		}
		,{ 
			'name':'Webinar Series #7 - Top Reasons & Guide to Move Your PBX Phone System to the Cloud',
			'contenttype': 'article',
			'logo':'dmm-7-236-144.jpg',
			'banner':'dmm-7-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Oct 19, 2016',
			'eventtime':'下午3:00-下午4:00',
			'expirydate':'2016-10-19T15:00:00+08:00',
			'location':'',
			'eventfor': ['IT专业人员'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Azure'],
			'description': '<p>“Moving to the Cloud” is a hot IT trend nowadays. More and more companies are moving their applications & services to the cloud but, have you ever thought about moving your PBX telephony system to the cloud? </p><p>Tune in to this webinar to discover the options available to you in the market and the benefits you stand to reap. Don\'t miss out on discovering the pre-requisites you should know of and also the steps to get started in moving your telephony system to the cloud.</p>',
			'regurl':'https://aka.ms/scf3dw',
			'gallery': ['']
		}
		,{ 
			'name':'Webinar Series #8 - How to Make Your Online Store Stand Out from the Crowd',
			'contenttype': 'article',
			'logo':'dmm8-236-144-10.jpg',
			'banner':'dmm8-630-236-10.jpg',
			'youtubeurl': '',
			'eventdate':'Nov 2, 2016',
			'eventtime':'下午3:00-下午4:00',
			'expirydate':'2016-11-02T15:00:00+08:00',
			'location':'',
			'eventfor': ['销售和市场专业人员'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': [''],
			'description': '<p>With growing online sales, developing an e-commerce website has become a trend for businesses. Online shopping is however, a competitive space. Building an e-Commerce website is easy but what does it take to build a great online store? </p><p>Tune in to this webcast featuring Vertex e-Commerce solution, a user-friendly web content management system. Discover essential tips & strategies to improve customer online shopping experience. Don\'t miss out on key learnings from case studies on success stories of how several online retailers improved customer interaction with this solution.</p>',
			'regurl':'https://aka.ms/uob2hf',
			'gallery': ['']
		}
		,{ 
			'name':'Webinar Series #9 - Is Your Restaurant POS Automating Sales with A Social Media Chatbot? ',
			'contenttype': 'article',
			'logo':'dmm9-236-144-07.jpg',
			'banner':'dmm9-630-236-07.jpg',
			'youtubeurl': '',
			'eventdate':'Nov 9, 2016',
			'eventtime':'下午3:00-下午4:00',
			'expirydate':'2016-11-09T15:00:00+08:00',
			'location':'',
			'eventfor': ['IT专业人员','销售和市场专业人员'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': [''],
			'description': '<p>Are you a restaurant owner using a traditional point-of-sale (POS) system and want to take your business to the next level? Did you know you can now leverage on social media to automate restaurant sales with an ordering Bot?</p><p>Join us in this webinar to learn how you can:<br/>• connect your restaurant POS menu to a Facebook ordering Bot and automate restaurant sales.<br/>• create a fully-responsive mobile website instantly for delivery, take-away orders and pre-ordered goods. <br/>• turn your restaurant POS into a social media and business hub.<br/>• engage and retain your customers.</p>',
			'regurl':'https://aka.ms/lm2r0k',
			'gallery': ['']
		}
		,{ 
			'name':'Webinar Series #10 - Enlightening Analytics for Logistics and Retail',
			'contenttype': 'article',
			'logo':'dmm10-236-144.jpg',
			'banner':'dmm10-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Nov 15, 2016',
			'eventtime':'下午3:00-下午4:00',
			'expirydate':'2016-11-15T15:00:00+08:00',
			'location':'',
			'eventfor': ['IT专业人员','销售和市场专业人员'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': [''],
			'description': '<p>Data can be your best buddy if you\'re able to unlock insights and effectively make use of it. Business Intelligence (BI), the art of sieving through large amounts of data, extracting information and turning it into actionable knowledge, is the key for your company to gain a competitive edge in the industry.</p><p>In this webinar, Bematek will share with you how you can leverage Microsoft Power BI to help propel your data management ability and ensure the right data and analytics are powering your business. Learn the key functions of Power BI and discover analytics reports made possible by this tool, such as: <br/>• Trending and top-N analysis with just a few clicks<br/>• Comparable store sales and team performance for accurate analysis <br/>• Variance analysis and alerts for informed and improved decision-making<br/>• Capability to get access to various on-premise and cloud data sources<br/>• Built-in data mining features providing insights you never had</p>',
			'regurl':'https://aka.ms/fjkf5n',
			'gallery': ['']
		}
		,{ 
			'name':'Webinar Series #11 - How to Win the China Market through Digital Marketing',
			'contenttype': 'article',
			'logo':'dmm11-236-144-08.jpg',
			'banner':'dmm11-630-236-08.jpg',
			'youtubeurl': '',
			'eventdate':'Dec 7, 2016',
			'eventtime':'下午3:00-下午4:00',
			'expirydate':'2016-12-07T15:00:00+08:00',
			'location':'',
			'eventfor': ['IT专业人员','销售和市场专业人员'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': [''],
			'description': '<p>How is your business responding to the effects of globalization especially with increased competition in the market? Are you thinking of penetrating into the China market but wondering what\'s the best way to do it? Do you know the unique marketing channels available to you specific to the China market? Tune in to this webinar to discover the 3 key steps to succeed in winning over the China market through digital marketing.</p>',
			'regurl':'https://aka.ms/mo7694',
			'gallery': ['']
		}
		,{ 
			'name':'Webinar Series #12 - Is Your Production Process Optimized for Client Collaboration?',
			'contenttype': 'article',
			'logo':'dmm12_236-144.jpg',
			'banner':'dmm12_630-236.jpg',
			'youtubeurl': '',
			'eventdate':'Dec 14, 2016',
			'eventtime':'下午3:00-下午4:00',
			'expirydate':'2016-12-14T15:00:00+08:00',
			'location':'',
			'eventfor': ['IT专业人员','销售和市场专业人员'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': [''],
			'description': '<p>Are you facing complexity in client collaboration and documentation during the product development and production process?<br/>Are you looking for a streamlined, action-monitored workflow to avoid production and delivery delays? <br/>Are you trying to secure future profit margins by controlling product costs as early as possible in the sample production stage?</p><p>Tune in to this webinar to find out how Cloudnifier\'s solution - MerchantPlus - can be your solution to all of the above. Discover how this innovative tool can help retailers, manufacturers and sourcing companies monitor product lifecycles from samples to finished products using best-practice procedures and guided workflows. It not only improves communication, boosts productivity and controls costs, but it also secures compliance with customer requirements and promised service standards.</p>',
			'regurl':'https://aka.ms/yamt6b',
			'gallery': ['']
		}
		,{ 
			'name':'Webinar Series #13 - Creating the Store of the Future',
			'contenttype': 'article',
			'logo':'dmm13_236-144.jpg',
			'banner':'dmm13_630-236.jpg',
			'youtubeurl': '',
			'eventdate':'Jan 5, 2017',
			'eventtime':'下午3:00-下午4:00',
			'expirydate':'2017-01-05T15:00:00+08:00',
			'location':'',
			'eventfor': ['IT专业人员','销售和市场专业人员'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': [''],
			'description': '<p>It is becoming an increasing challenge to capture today’s empowered and ever-changing shoppers—especially in-store. To survive, retailers must start capturing and use shopper insights in real-time.</p><p>Tune in to this webinar to learn:<br/>• Critical metrics to measure in-store success in retailing today<br/>• How to capture 24/7 shopper insights in-store without physical manpower<br/>• Ways to use real-time insights and digital signage to drive desired shopper behaviors and sales in-store</p>',
			'regurl':'https://aka.ms/r6pg5u',
			'gallery': ['']
		}
		,{ 
			'name':'Webinar Series #14 - Are You Unlocking Business Value from The Internet of Your Things?',
			'contenttype': 'article',
			'logo':'dmm14_236-144.jpg',
			'banner':'dmm14_630-236.jpg',
			'youtubeurl': '',
			'eventdate':'Jan 12, 2017',
			'eventtime':'下午3:00-下午4:00',
			'expirydate':'2017-01-12T15:00:00+08:00',
			'location':'',
			'eventfor': ['IT专业人员'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': [''],
			'description': '<p>The Internet of Things (IoT) is firmly here, but many organizations are still wondering where to start. The IoT is transforming the way many organizations operate. Forward-thinking executives will have a big role to play in the implementation of IoT solutions. As businesses start to explore how IoT could fit into their organizations, it can quickly become overwhelming, but it doesn\'t need to be. This webinar\'s practical experience in how to start with the Internet of Your Things can simplify this.</p><p>Tune in to this webinar to:<br />• Start - Learn how you can start with ‘things’ you already have, to get more out of your existing assets. Start small for big impact by optimizing key areas of your existing business to help it thrive.<br />• Discover - Discover how to connect people, devices, sensors, and infrastructure to unlock valuable business insights that empower employees to make informed decisions.<br />• Learn - Learn how to integrate intelligent systems to gain greater insights that delight customers and unlock new opportunities. <br />• Discuss - Discuss real examples of how these assets can be connected, opening them up to the opportunities of data analytics, to solve real business problems.</p>',
			'regurl':'https://aka.ms/evh1lz',
			'gallery': ['']
		}
		,{ 
			'name':'Webinar Series #15 - Has your business started automating sales via a mobile app?',
			'contenttype': 'article',
			'logo':'dmm15_236-144.jpg',
			'banner':'dmm15_630-236.jpg',
			'youtubeurl': '',
			'eventdate':'Jan 18, 2017',
			'eventtime':'上午10:00-上午11:00',
			'expirydate':'2017-01-18T11:00:00+08:00',
			'location':'',
			'eventfor': ['IT专业人员'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Azure'],
			'description': '<p>Imagine if your business has a mobile app that helps you automate sales tasks, including order processing, customer management, contact management, inventory monitoring & control, order tracking, sales forecast analysis, even down to staff performance evaluation. Imagine the improvement in customer service you\'re able to offer if you can do all of the above.</p><p>Benefits of automating your sales process via a mobile app:<br />• Reduce Costs - automating the sales process improves efficiency and reduces overhead costs.<br />• Improve Customer Experience - instant quotation and self-ordering features help improve customer experience.<br />• Increase Customer Loyalty - ability to capture and analyze sales data with intelligent business tools help you customize marketing programs for increased customer loyalty.<br />• Increase Sales - improved efficiency, reduced costs and improved customer experience, all ultimately lead to increase in sales.</p><p>If you are considering developing a mobile app to automate sales and improve customer experience, tune in to this webinar to gain insights on:<br />• Mobile App Sales Automation – What it is and how it can help improve customer experience, reduce costs and increase business efficiency.<br />• Mobile App Development – Things to evaluate and how to find a trusted partner who fits your business needs.<br />• Best Practice Case Study - Learn from the best, see how e-print and e-banner have leveraged mobile app sales automation to transform their business.</p>',
			'regurl':'https://aka.ms/ie530i',
			'gallery': ['']
		}
		,{ 
			'name':'Hands-on Bootcamp: Oracle Database Migration',
			'contenttype': 'article',
			'logo':'oracle-camp_236-144.jpg',
			'banner':'oracle-camp_630-236.jpg',
			'youtubeurl': '',
			'eventdate':'Jan 16, 2017 - <br />Jan 19, 2017',
			'eventtime':'上午9:30-下午6:00',
			'expirydate':'2017-01-19T09:30:00+08:00',
			'location':'15/F, Microsoft Office, Cyberport 2, 100 Cyberport Road',
			'eventfor': ['IT专业人员'],
			'eventtype': ['技术培训'],
			'category': [''],
			'product': ['Server and Management'],
			'description': '<p>Leverage the competitive SQL Server license offers and assist customers in their journey to the Microsoft Data Platform. Gain the skills to bring the reality of a successful competitive database migration to your customers today.</p><p>There has never been a better time for customers to migrate from Oracle.</p><p>SQL Server 2016 now leads in the Gartner magic quadrant for commercial operational databases and top TPC performance benchmarks. Customer demand is spiking to take advantage of the innovation, security and performance benefits that comes with SQL Server 2016 and Azure Data Services.</p><p>This 4-day curriculum is specifically designed to accelerate an Oracle to SQL migration partner practice. Delivered by 2 industry experts, who will share insights and best practices from the Microsoft Migration Center of Excellence consulting group.</p><p>Attendees will leave the training armed with the skills to qualify and complete an Oracle to SQL database migration project.</p><p>Act now! Take advantage of this opportunity to expand your database services practice and include a migration competency.</p>',
			'regurl':'https://www.microsoftevents.com/profile/form/index.cfm?PKformID=0x1138975b906',
			'gallery': ['']
		}
		,{ 
			'name':'Tech Summit 2017',
			'contenttype': 'article',
			'logo':'techsummit-236-144.jpg',
			'banner':'techsummit-630-236.jpg',
			'youtubeurl': '',
			'eventdate':'Feb 14, 2017 - <br />Feb 15, 2017',
			'eventtime':'上午9:00-下午6:00',
			'expirydate':'2017-02-15T09:00:00+08:00',
			'location':'Hong Kong Convention and Exhibition Centre, 1 Expo Drive, Wanchai',
			'eventfor': ['IT专业人员'],
			'eventtype': ['技术培训'],
			'category': ['网络研讨会'],
			'product': [''],
			'description': '<p>Annual premier technology event delivered by international experts in more than 16 global locations.<br/>Transformational trainings designed for IT decision makers, IT professionals and developers.<br/>Hands-on experience and networking opportunities with a global IT community.<br/>Gather expert knowledge you can apply right away – whether you are tech-savvy or just getting started. You will learn about the most exciting trends and best practices from top local and Microsoft corporate speakers on products and platforms such as Azure, Dynamics 365, Office 365 and Windows 10.</p><p>Over 50 technical breakouts will be offered across a broad range of hot topics including productivity, security, networking, big data, storage, unified communications, collaboration, hybrid cloud, open source, DevOps and IoT.</p>',
			'regurl':'https://aka.ms/mshkts17eh',
			'gallery': ['']
		},{ 
			'name':'Webinar Series #16 - Turning Digital Strangers into Delighted Customers',
			'contenttype': 'article',
			'logo':'dmm16_236-144.png',
			'banner':'dmm16_630-244.png',
			'youtubeurl': '',
			'eventdate':'Feb 8, 2017',
			'eventtime':'上午10:00-上午11:00',
			'expirydate':'2017-02-08T11:00:00+08:00',
			'location':'',
			'eventfor': ['IT专业人员'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Azure'],
			'description': '<p>Are you effectively converting anonymous leads into customers? Or engaging deeply with loyal customers? Marketers and digital leaders can only bring customer experience to its fullest when they’re marketing in context of customers’ multiple footprints – be it online, mobile or in-store interactions. Successful contextual marketing allows you to talk to customers with the best relevancy at the right time and the right place.</p><p>This is where business intelligence kicks in to allow marketers to deliver customized interactions that delight audience, build loyalty, and ultimately drive revenue.</p><p>Tune in to this webinar to learn how to successfully employ contextual marketing in your own organization and turn digital strangers into delighted customers.</p>',
			'regurl':'https://aka.ms/dbp6jx',
			'gallery': ['']
		},{ 
			'name':'【Tech Training】Deploy and Defend Windows Clients from Modern Threats with Windows 10 Security',
			'contenttype': 'article',
			'logo':'tech-training-236-144.jpg',
			'banner':'tech-training-630-234.jpg',
			'youtubeurl': '',
			'eventdate':'Mar 20, 2017',
			'eventtime':'上午9:00-下午5:00',
			'expirydate':'2017-03-20T17:00:00+08:00',
			'location':'Feva Works IT Education Centre, Cheung Sha Wan',
			'eventfor': ['IT专业人员','开发人员'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Windows'],
			'description': '<p>Windows 10 offers an enormous leap forward when it comes to threat resistance, but that is just the beginning. In this Tech Training, you will learn the impressive lineup of new Windows 10 capabilities including WDATP and Creators Update, along with deployment knowledge to raise the security bar even further for malware and other online threats.</p>',
			'regurl':'https://aka.ms/tawuuo',
			'gallery': ['']
		},{ 
			'name':'Webinar Series #17 - Building Customer Loyalty through Personalization',
			'contenttype': 'article',
			'logo':'DMM17_236-144.jpg',
			'banner':'DMM17_630-244.jpg',
			'youtubeurl': '',
			'eventdate':'Mar 1, 2017',
			'eventtime':'上午10:00-上午11:00',
			'expirydate':'2017-03-01T11:00:00+08:00',
			'location':'',
			'eventfor': ['IT专业人员'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Dynamics','Power BI'],
			'description': '<p>Driving customer loyalty through a well-established membership system and attractive incentive scheme is in the heart of businesses. However, not all the analytic tools are able to support customized functions.</p><p>This is where Omni-channel Marketing comes in to allow businesses to capture and access valuable data, enabling them to deliver more targeted and personalized customer messages and experience, where they can also achieve a win-win situation with upsell and cross-sell opportunities.</p><p>Tune into this webinar to gain insights on how to engage deeper with customers with a comprehensive and integrated membership management journey, including member recruitment and profiling, real time membership points calculation and reward redemptions, promotion management as well as touchpoint integration with, web portal, mobile app and social network with Power BI analytic services.</p>',
			'regurl':'https://aka.ms/qfhl8c',
			'gallery': ['']
		},{ 
			'name':'Webinar Series #18 - Driving Business Performance from Zero to 100',
			'contenttype': 'article',
			'logo':'DMM18_236-144.jpg',
			'banner':'DMM18_630-244.jpg',
			'youtubeurl': '',
			'eventdate':'Mar 15, 2017',
			'eventtime':'上午10:00-上午11:00',
			'expirydate':'2017-03-15T11:00:00+08:00',
			'location':'',
			'eventfor': ['IT专业人员'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Office','Microsoft Dynamics','Power BI'],
			'description': '<p>Are you adopting workflow automation systems effectively to drive your business? In this digital transformation era, it is crucial for business users to develop the ability to perform lightweight, self-service data, as well as application creation and integration to cope with the ever-changing environment. Workflow automation allows users to connect with the cloud, data and apps easily, enabling them to work and collaborate anytime, anywhere. </p><p>Tune into this webinar to learn the best practice of how to design and acquire modern workflow and content automation apps for companies to meet the ever-changing needs of business users. </p>',
			'regurl':'https://aka.ms/s96xtl',
			'gallery': ['']
		},{ 
			'name':'MSX // IoT',
			'contenttype': 'article',
			'logo':'iot-236-144.jpg',
			'banner':'iot-630-236.jpg',
			'youtubeurl': '',
			'eventdate':'Oct 13, 2016',
			'eventtime':'下午3:00-下午6:00',
			'expirydate':'2016-10-13T18:00:00+08:00',
			'location':'Microsoft Experience Center',
			'eventfor': ['业务管理者'],
			'eventtype': ['研讨会及会议'],
			'category': ['线下会议'],
			'product': [''],
			'description': '<p>The Internet of Things (IoT) is your first step in becoming a truly digital business. It is a practical and applicable technology trend that can generate return on investment (ROI) and drive efficiencies and insights for organizations that know how to use it. At Microsoft, we believe IoT can make a difference to your business right now—beginning with the things in your business that matter the most. </p><p>MSX // IoT will feature keynote speakers who will demystify IoT and explore opportunities for you to harness the IoT revolution and make it work for your business. Discover new insights and possibilities with our featured partners in the Innovation Showcase Tour. Come learn how you can create more business value using your existing technology assets.</p><p>Microsoft Experience (MSX) is a series of events featuring curated innovation showcases. Microsoft MSX // IoT is a specialist edition of the Microsoft Experience. </p>',
			'regurl':'#',
			'gallery': ['']
		},{ 
			'name':'MSX // Financial Services',
			'contenttype': 'article',
			'logo':'fs-236-144.jpg',
			'banner':'fs-630-236.jpg',
			'youtubeurl': '',
			'eventdate':'Aug 16, 2016',
			'eventtime':'下午3:00-下午6:00',
			'expirydate':'2016-08-16T18:00:00+08:00',
			'location':'Microsoft Experience Center',
			'eventfor': ['业务管理者'],
			'eventtype': ['研讨会及会议'],
			'category': ['线下会议'],
			'product': [''],
			'description': '<p>MSX // Financial Services is a technology solution showcase organized by Microsoft and is geared towards the financial services industry. Featuring keynote speakers, live demos, solution showcase and interactive conversations, the event will explore trends, disruptive technology as well as other hot topics impacting the financial services landscape. </p>',
			'regurl':'#',
			'gallery': ['']
		},{ 
			'name':'MSX // Retail',
			'contenttype': 'article',
			'logo':'retail-236-144.jpg',
			'banner':'retail-630-236.jpg',
			'youtubeurl': '',
			'eventdate':'May 12, 2016',
			'eventtime':'下午3:30-下午6:30',
			'expirydate':'2016-05-12T18:00:00+08:00',
			'location':'Microsoft Experience Center',
			'eventfor': ['业务管理者'],
			'eventtype': ['研讨会及会议'],
			'category': ['线下会议'],
			'product': [''],
			'description': '<p>What you can expect from MSX // Retail<br>• Innovation – Find out how to weather the worst retail sales slump in 17 years through digital transformation.<br>• Insight – Stay ahead of the curve with an exclusive preview of cutting-edge technology in retail.<br>• Ideas – Take away fresh ideas in retail to accelerate your business and delight your customers.</p>',
			'regurl':'#',
			'gallery': ['']
		},{ 
			'name':'MSX // Marketing, Media & Communications',
			'contenttype': 'article',
			'logo':'msx-marketing-236-144-eh.jpg',
			'banner':'msx-marketing-630-236-eh.jpg',
			'youtubeurl': '',
			'eventdate':'Mar 14, 2017',
			'eventtime':'下午3:00-下午6:00',
			'expirydate':'2017-03-14T18:00:00+08:00',
			'location':'Microsoft Experience Center',
			'eventfor': ['销售和市场专业人员'],
			'eventtype': ['研讨会及会议'],
			'category': ['线下会议'],
			'product': [''],
			'description': '<p>A good marketing strategy plays a critical role in driving business success and impact. Utilizing the right marketing tools and solutions is key to achieving this success.</p><p>MSX // Data Insights is a technology showcase event organized by Microsoft Hong Kong featuring the future of intelligent systems with data insights solutions. This event will also feature Microsoft\'s Smart City solutions, demonstrating how Microsoft is empowering cities to transform their operations and citizen services and foster economic development with a people-first approach.</p><p>Microsoft Experience (MSX) is a series of events featuring curated innovation showcases for different industries. Microsoft MSX // Marketing, Media & Communications is a specialist edition of the Microsoft Experience.</p>',
			'regurl':'#',
			'gallery': ['']
		}
];


var db_filter = [
       { 
			'section':'活动受众人群',
			'type':'eventfor',
			'filter': [
			              {'type':'eventfor','name':'销售和市场专业人员'}, 
						  {'type':'eventfor','name':'IT专业人员'}, 
						  {'type':'eventfor','name':'开发人员'}, 
						  {'type':'eventfor','name':'教育工作者'}, 
						  {'type':'eventfor','name':'中小型企业经营者'},
			   	          {'type':'eventfor','name':'业务管理者'},
						  {'type':'eventfor','name':'IT管理者'}
			]
	   }
	   ,{ 
			'section':'活动分类',
			'type':'eventtype',
			'filter': [
			              {'type':'eventtype','name':'技术培训'}, 
						  {'type':'eventtype','name':'研讨会及会议'},
						  {'type':'eventtype','name':'在线会议回放'},
						  {'type':'eventtype','name':'解决方案演示'}
			]
	   }
	   ,{ 
			'section':'活动形式',
			'type':'category',
			'filter': [
			              {'type':'category','name':'线下会议'},
						  {'type':'category','name':'网络研讨会'}
			]
	   }
	   ,{ 
			'section':'活动时间',
			'type':'eventtime',
			'filter': [
			              {'type':'eventtime','name':'即将发生'}, 
						  {'type':'eventtime','name':'以往活动'}
			]
	   }
	   ,{ 
			'section':'产品分类',
			'type':'product',
			'filter': [
			              {'type':'product','name':'Developer Tools'},
						  {'type':'product','name':'Devices & Xbox'},
						  {'type':'product','name':'Hololens'},
						  {'type':'product','name':'Microsoft Azure'},
						  {'type':'product','name':'Microsoft Dynamics'},
						  {'type':'product','name':'Office'},
						  {'type':'product','name':'Power BI'},
						  {'type':'product','name':'Server and Management'},
						  {'type':'product','name':'Skype'},
						  {'type':'product','name':'Windows'}
			]
	   }
];

var db_banner = [
	   
       { 
			'desktopbanner':'tech-academy-desktop.jpg',
			'mobilebanner':'tech-academy-mobile.jpg',
			'url':'#TechAcademy'
	   },
	   { 
			'desktopbanner':'dmm-web.jpg',
			'mobilebanner':'dmm-mobile.jpg',
			'url':'#Webinar'
	   },
	{ 
			'desktopbanner':'msx-mkt-desktop-banner.jpg',
			'mobilebanner':'msx-mkt-mobile-banner.jpg',
			'url':'#msx'
	   }

];

var db_promotion = [{
    'section': 'Event Series',
    'filter': '网络研讨会',
    'contenttype': 'article',
    'banner': 'webinar-detail-desktop.jpg',
    'youtubeurl': ''
},{
    'section': 'Event Series',
    'filter': 'Tech Academy',
    'contenttype': 'article',
    'banner': 'tech-academy-details.jpg',
    'youtubeurl': ''
}]

