var db_product = [
        { 
			'name':'Apptask Limited',
			'logo':'Apptask.jpg',
			'industry': ['跨行業'], 
			'product': ['Microsoft Azure'],
			'contact':'Him Cho',
			'phone': '(852) 3487-9549',
			'email': 'him.cho@Apptask.com',
			'website': 'www.apptask.com',
			'description': '<strong>TeamNote</strong><ul><li>以雲端為基礎的流動協作工具</li><li>包括即時通訊/ 圖像匯報/ 檔案轉送/調查及投票 / 工作派遣</li><li>工作支援、文件和培訓管理、前線銷售活動報告和團隊通訊</li></ul><br /><strong>EventMaster</strong><ul><li>企業活動策劃解決方案</li><li>包括電郵發佈/ 提名/ 報到/ VIP溫馨提示/ 評估/ 統計報告</li><li>支援QR碼/ Passbook / NFC </li></ul><br /><strong>所部署的 Microsoft 技術</strong><ul><li>ASP.Net MVC4</li><li>Azure 雲端運算</li><li>AES 256加密</li><li>Messaging Broker: RabbitMQ</li><li>Long Polling</li><li>Push Notification</li><li>SSL Certificate</li></ul><br /><strong>目標客戶規模</strong><ul><li>TeamNote 10人至50,000人</li><li>EventMaster 100人以上</li></ul>'
		},
		{ 
			'name':'Avrio Solutions Company Limited',
			'logo':'Avrio.jpg',
			'industry': ['教育'], 
			'product': ['Microsoft Azure'],
			'contact':'Zorro Cheng',
			'phone': '',
			'email': 'zorro.cheng@avrio.hk',
			'website': 'www.avriohk.com',
			'description': '<ul><li>eSchoolPad是一個以雲端為基礎的流動裝置管理 (MDM)解決方案，專為教育界而設，讓教師及家長能以開放態度面對子女於課堂及家中使用流動裝置。 </li> <li>課堂管理</li> <li>應用程式管理</li><li>安全管理</li> <li>自攜設備 (個人裝置) 支援</li> <li>支援Apple VPP</li></ul><br /><strong>所部署的 Microsoft 技術</strong><br />Microsoft Azure<br /><br /><strong>目標客戶規模</strong><ul><li>香港: 400間學校 (@50 裝置 )</li><li>台灣: 800間學校 (@100 裝置) </li></ul>'
		},   
		{ 
			'name':'Big Dipper Studio Limited',
			'logo':'Big_Dipper.jpg',
			'industry': ['教育'], 
			'product': ['Kinect', 'Microsoft Azure', 'Windows'],
			'contact':'William Chan',
			'phone': '(852) 3526-0616',
			'email': 'william@bigdipperstudio.com',
			'website': 'www.bigdipperstudio.com',
			'description': '<ul><li>Space Racer 是一個跨平台的電子學習解決方案。學生完成賽車比賽後可升級其賽車。於每場賽事，他們需要正確回答問題以通過關卡。完成賽事的時間越快，所得的排名便越高。Space Racer支援桌上電腦、平板電腦和Kinect v2，並同一時間支援最多四位玩家參與遊戲及學習，為學生提供富趣味的學習氣氛。教師亦可於報告系統上查看學生表現。 </li><li>Occupational Safety Task Force由Macau DSAL (澳門勞工事務局) 開發，是一個為建築業、酒店業和飲食業的員工而設的培訓遊戲。此遊戲以Kinect打造各個行業的遊戲場景，以推廣工作健康與安全。現時已設於澳門科學館開放給公眾試玩。</li></ul><br /><strong>所部署的 Microsoft 技術</strong><br /><ul><li>Microsoft Kinect V2</li><li>Microsoft Kinect V1</li></ul><br /><strong>目標客戶規模</strong><br /><ul><li>所有小學 (香港: 569間小學) 和6至12歲兒童 (320,918 學生)</li><li>澳門公民 (624,000 人)</li></ul>'
		}, 
		{ 
			'name':'DocuSign',
			'logo':'DocuSign.jpg',
			'industry': ['數碼行銷'], 
			'product': ['Windows', 'Windows Phone'],
			'contact':'',
			'phone': '',
			'email': '',
			'website': 'www.docusign.com',
			'description': '<ul><li>以三藩市及西雅圖為基地的DocuSign提供達全球標準的電子交易管理方案，當中包括電子簽署技術及電子交易管理服務，促進電子合約及已簽署文件的傳送。此外，DocuSign亦提供認證服務、用戶身份管理及工作流程自動化功能。</li> <li>專為Windows而設的DocuSign，有助用戶隨時隨地進行電子簽署、發送及儲存文件。</li> <li>DocuSign既安全又保密，同時具法律約束力。用戶可縮減工作時間，更無需列印、傳真、掃瞄或通宵等待文件。</li> <li>DocuSign可同時滿足個人及工作上的需要，如保密文件、職員表格、租賃協議、合約、收據、工作訂單、銷售單據、同意書等等。</li> </ul><br /><strong>所部署的MS科技</strong><ul><li>Windows Client</li><li>Windows Phone</li></ul>'
		},
		{ 
			'name':'EmployeeConnect (Greater China) Limited',
			'logo':'Employee_connect.jpg',
			'industry': ['跨行業'], 
			'product': ['Microsoft Azure', 'Power BI', 'SQL Server'],
			'contact':'Mr. Alex Lum',
			'phone': '(852)  3104-8200',
			'email': 'Alex.Lum@EmployeeConnect.com.hk',
			'website': 'www.employeeconnect.com.hk',
			'description': '<strong>EmployeeConnect Cirrus</strong><ul><li>雲端上傳遞的企業級HR解決方案，包含HR、工資表、考勤、審核、人才發展管理，以及員工和經理自助服務的相關功能。</li><li>由Microsoft Power Pivot和Power BI支持，內置報告及業務智能工具。 </li> <li>模塊化設計，你所選擇的模塊可用作捆綁式解決方案或原有系統上添加。</li> <li>另外亦可以內部部署的形式使用EmployeeConnect HR-Enterprise。</li></ul><br /><strong>所部署的 Microsoft 技術</strong><ul><li>Windows Azure</li><li>置於Azure上的SQL Server 2014 – Enterprise</li><li>SQL Server Analysis Service</li><li>Power Pivot及Power BI</li></ul><br /><strong>目標客戶規模</strong><br />員工數目由100 人至 1,000人'
		},
        { 
			'name':'Everyware Limited',
			'logo':'everyware.jpg',
			'industry': ['零售業、酒店業、消費行業'], 
			'product': ['Microsoft Azure', 'SQL Server'],
			'contact':'Billy Chan',
			'phone': '(852) 3998-9168',
			'email': 'billy.chan@everyware.com.hk',
			'website': 'www.everyware.com.hk',
			'description': '<ul><li>功能比任何傳統飲食業POS市場競爭者更具優勝</li> <li>為餐廳而設，首個以雲端為基礎的POS </li>  <li>具備專有同步技術，可與Windows Azure同步</li>  <li>實時整體快照，方便了解餐廳狀況</li>  <li>大數據及商業智能分析</li>  <li>開放API，連接任何其他應用程式或平台界面 (e.g. 51wm)</li>  <li>可連接社交媒體如 Facebook、微博及微信</li>  <li>支援以智能手機及平板電腦的進行場外餐廳管理</li> </ul><br /><strong>所部署的 Microsoft 技術</strong><br />Windows Azure、WPF、WCF、SQL 伺服器等等 <br /><br /><strong>目標客戶規模</strong><ul><li>餐廳</li><li>設有分店的餐廳</li><li>連鎖式餐廳</li></ul>'
		},
		{ 
			'name':'Holumino Limited',
			'logo':'Holumino.jpg',
			'industry': ['零售業、酒店業、消費行業'], 
			'product': ['Microsoft Azure', 'Windows', 'Xbox'],
			'contact':'Nicole Or',
			'phone': '(852) 6018-4756',
			'email': 'nicole.or@holumino.com',
			'website': 'www.holumino.com',
			'description': '<p>移動追蹤的安裝程式，讓用戶不需穿著虛擬現實設備也能感受3D體驗。我們轉化2D成3D，並把空間和產品設計視像化。</p><strong>所部署的 Microsoft 技術</strong><br />移動追蹤，實時繪製<br /><br /><strong>目標客戶規模</strong><br />地產展覽商、家具公司、室內設計、購物商場等等'
		},
		{ 
			'name':'Integrated Solutions Limited',
			'logo':'IS.jpg',
			'industry': ['跨行業'], 
			'product': ['Microsoft Azure', 'Microsoft Dynamics', 'Office', 'Windows', 'Windows Server', 'SQL Server'],
			'contact':'Kate Chan',
			'phone': '(852) 2263-6104',
			'email': 'katec@isl.com.hk',
			'website': 'www.isl.com.hk',
			'description': '<p>ReportNOW是一套適合所有行業的流動數據交換平台。只要手上有任何一種流動裝置便能<strong>無間斷地接收或更新業務信息</strong>。<br />此外，所接收的信息並無限制，用戶可把即時收集到的信息實時上載到公司的數據庫。<br />透過ReportNOW，您可以將智能手機、平板電腦連接到現有的數據系統，取得<strong>實時的數據</strong>建立報表，以及<strong>將智能手機上收集的信息實時上載到公司的數據庫</strong>，令您工作更有效率。</p><ul><li>安裝容易，用法簡單</li><li>兼容不同數據庫</li><li>於<strong>各個平台</strong>提供多元化格式的實時匯報</li></ul><br /><strong>所部署的 Microsoft 技術</strong><ul><li>Back End (Microsoft Dynamics, SQL Server)</li><li>App Server (Windows Server 2012, IIS8)</li><li>Client Device (Windows 8.1, Office)</li></ul><br /><strong>目標客戶規模</strong><br />中小型'
		}, 
		{ 
			'name':'K2',
			'logo':'K2.jpg',
			'industry': ['跨行業'], 
			'product': ['SharePoint', 'Microsoft Dynamics', 'Office', 'Microsoft Azure'],
			'contact':'',
			'phone': '',
			'email': '',
			'website': 'www.k2.com',
			'description': '<p>K2軟件讓用戶建立及執行業務流程應用程式，包括表格、工作流程、數據及報告，更可與Office 365、Dynamics CRM、SQL Server、Azure Media Services等重要的業務系統進行整合。</p><p>K2一直協助Microsoft客戶透過SharePoint伺服器技術部署解決方案。K2與SharePoint Server 2010的整合造就了強大的用戶基礎，在無須編碼的情況下， SharePoint 2010可製作詳盡的工作流程和流程主導的應用程式。</p><p>利用K2領先的Microsoft Dynamics CRM 整合方案，用戶可以把客戶的數據加到個人化的表格，隨時隨地更快捷地獲取所需數據及進行決策。</p>'
		}, 
		{ 
			'name':'KBQuest Group Inc.',
			'logo':'KBQuest.jpg',
			'industry': ['跨行業'], 
			'product': ['Microsoft Azure', 'Windows', 'SQL Server', 'Office', 'SharePoint'],
			'contact':'Eric Moy',
			'phone': '(852) 2180-8612',
			'email': 'emoy@kbquest.com',
			'website': 'www.kbquest.com/index.php?page=content/home',
			'description': '<p>My Learning Companion 365 (MLC365) – 置於Office 365 平台上的網上課程和文件管理系統。MLC365提供Office 365的功能，促進教師、學生和行政人員之間的協作、輔導和溝通。</p><strong>所部署的 Microsoft 技術</strong><ul><li>Microsoft Azure</li><li>Microsoft Office 365</li><li>Microsoft Windows Store App</li><li>Microsoft SQL Server</li><li>Microsoft SharePoint Server</li></ul><br /><strong>目標客戶規模</strong><br />1000位以上用戶'
		}, 
		{ 
			'name':'Modern Educational Digital Media Limited',
			'logo':'MEDM.jpg',
			'industry': ['教育'], 
			'product': ['Microsoft Azure', 'Windows'],
			'contact':'',
			'phone': '(852) 2786-1322',
			'email': 'enquiry@moderndm.com',
			'website': 'www.moderndm.com',
			'description': '<p>MERS eTextbook 為一個應用程式，方便用戶下載由現代教育研究社有限公司出版的電子圖書，並支援出版各式各樣的校本電子圖書。</p><strong>MERS eTextbook的特點:</strong><ul> <li>eTextbook 提供範圍廣泛的eTextbooks，包括各科目的教科書及故事書。</li> <li>此應用程式可於用戶登入後辨識其訪問權限，然後根據用戶所屬學校及年級，提供適當的eTextbooks。(包括校本教科書) </li><li>每本eTextbook均內置實用工具，例如筆記本、繪畫工具等等。</li> <li>eTextbooks內容豐富，整合了影片、音頻教材、圖片等等。</li> <li>eTextbooks亦包含互動式活動，用戶可追蹤其學習歷程及成果。</li> </ul><br /><strong>所部署的 Microsoft 技術</strong><ul><li>Windows 平台上運行的APPs 及Executable Programmes </li><li>託管在Microsoft Azure上的終端</li></ul><br /><strong>目標客戶規模</strong><br />大約600,000 名香港及澳門的幼稚園、小學及中學生'
		},
		{ 
			'name':'Play More Limited',
			'logo':'Playmore.jpg',
			'industry': ['傳媒娛樂'], 
			'product': ['Microsoft Azure'],
			'contact':'Alex Lau',
			'phone': '(852) 5198-2099',
			'email': '',
			'website': 'www.playmore.com.hk',
			'description': '<p>Team More是一個自攜設備 (BYOD)綜合企業解決方案，由九個軟件模塊組成 (於iOS和Android平台提供)，以滿足不同通訊需要。特點及功能包括: 新聞發佈、活動日曆共享、電子通訊刊物、產品目錄、文件檔雲存儲、社交平台、流動培訓平台、電子表格和企業專用的即時通訊軟件。有別於其他功能及特點已固定的手機應用程式 (如Google應用程式)，Team More個性化及可擴張的特點更能符合不同組織的需要。</p><strong>所部署的 Microsoft 技術</strong><ul><li>Microsoft Azure Web Sites & Web Jobs</li><li>Microsoft Azure儲存體 & CDN</li><li>Microsoft Azure虛擬機器 (托管MariaDB和Push Notification Services)</li><li>Microsoft Azure媒體服務</li><li>Microsoft Azure 虛擬網路</li><li>AD FS Integration</li></ul><br /><strong>目標客戶規模</strong><br />企業或組織 (1) 具有高流動性的員工; (2) 具有較強的溝通需求，而公司信息需要及時傳達給員工。我們的目標行業的例子有航空、建築、連鎖式零售、會所、酒店等等'
		},
		{ 
			'name':'Quantifeed HK Limited',
			'logo':'Quantifeed.jpg',
			'industry': ['金融服務'], 
			'product': ['Microsoft Azure', 'Office', 'SQL Server', 'Visual Studio'],
			'contact':'Ross Milward',
			'phone': '(852) 3105-9610',
			'email': 'ross.milward@quantifeed.com',
			'website': 'www.quantifeed.com',
			'description': '<ul><li>於亞洲的大眾富裕階層市場*以經濟實惠的價錢提供網上理財產品，並不設最低財富金額限制</li> <li>通過自動化一部分投資過程，加上採用獲得諾貝爾獎的財務模型和雲託管網絡技術，建立易於存取的高透明度產品，並與長期合作的業務伙伴為目標顧客提供其他金融服務。</li></ul><p>*大眾富裕階層為全球增長得最快，特別是亞洲的富裕階層，其個人可投資資產總值10萬至100萬美元。他們通常被主流理財供應商所忽略，因該類供應商集中服務更富裕的階層。</p><strong>所部署的 Microsoft 技術</strong><ul><li>Azure (Web Sites、背景工作角色、虛擬機器、虛擬網路、SQL DB、SQL Sync、流量管理員、排程器)</li><li>Visual Studio Online</li><li>Visual Studio 2013</li><li>C# / ASP.NET MVC / ASP.NET WebApi / TypeScript</li><li>Office 365 </li></ul><br /><strong>目標客戶規模</strong><ul><li>由於Quantifeed是B2B2C平台，我們的目標客戶為: 消費者銀行、財務策劃員、網上經紀及CFD供應商，以及單戶家族理財室和多戶家族理財室。最終，我們的產品能夠透過業務合作夥伴到達大眾富裕階層市場。</li><li>亞洲共有四千萬人擁有資產高達$12萬億美元，屬大眾富裕階層。新一代富裕人士較年輕、獨立且精通科技– 他們希望以自己的金錢進行投資。此創造了巨大的商機予提供具高度擴展性產品的公司，並於五年內年度營業額已高於二千萬美金。</li></ul>'
		},
		{ 
			'name':'SCHMIDT-iSOFT LIMITED',
			'logo':'SCHMIDT-iSOFT.jpg',
			'industry': ['跨行業'], 
			'product': ['Microsoft Azure', 'SQL Server', 'Windows Server', 'Power BI'],
			'contact':'Candice Han',
			'phone': '(852) 2507 0264',
			'email': 'candicehan@schmidt-isoft.com',
			'website': 'www.schmidt-isoft.com',
			'description': '<p>PARROT語音解決方案利用語音指令執行及操作倉庫，能有效改善物流中心的生產力及安全性。</p><p>EAGLE系列的企業移動解決方案，支援技術員於任何時間或地點均可透過移動裝置登入移動應用程式，了解員工的工作情況。</p><ul><li>Mobile Proof of Delivery 移動送驗證</li><li>Mobile Sales and Delivery 移動車銷配送</li><li>Mobile Store Inspection 移動巡店</li><li>Mobile Pickup and Delivery 移動押運</li><li>Mobile Meter Reading  移動抄表</li></ul><br /><strong>目標客戶規模</strong><br /><ul><li>中型至大型企業</li></ul><br /><strong>所部署的MS技術</strong><br /><ul><li>Microsoft Azure/ SQL Azure</li><li>SQL Server/ Windows Server</li><li>Xamarin</li><li>Power BI/ Microsoft BI</li><li>Microsoft SOA</li></ul><br /><strong>客戶參考</strong><br /><ul><li>Café de Coral 大家樂</li><li>Zuellig Pharma 裕利醫藥</li><li>Towngas 香港中華煤氣</li><li>Beijing Water Supply</li><li>SinoTrans/ DHL中國外運(香港) 物流/ DHL</li><li>Carlsberg 嘉士伯</li><li>Vitasoy維他奶</li><li>Crown Logistics皇冠物流</li><li>Kerry Logistics嘉里物流</li></ul>'
		},
		{ 
			'name':'sitecore',
			'logo':'Digital_Marketing.jpg',
			'industry': ['數碼行銷'], 
			'product': ['Microsoft Azure'],
			'contact':'',
			'phone': '',
			'email': '',
			'website': 'www.sitecore.net',
			'description': '<p>Sitecore Azure 是一個用於數碼營銷的雲端顧客體驗解決方案。銷售人員可利用Sitecore Azure，得知每位顧客與品牌間的互動，以及透過不同渠道獲取顧客的青睞。</p><p>Sitecore Azure是一個專為Azure PaaS部署而設，由Sitecore建立及管理的模型。Sitecore Azure能夠協助用戶輕鬆於Azure進行部署、擴展和管理Sitecore環境(授權及交付實例)。</p><strong>所部署的MS技術</strong><br />Microsoft Azure<br /><br /><strong>目標客戶規模</strong><br /><ul><li>約400間香港學校 (每間共50 個裝置)</li><li>約800間台灣學校 (每間共100 個裝置) </li></ul><br /><strong>客戶參考</strong><br /><ul><li>Revlon 露華濃</li><li>Carrefour 家樂福</li></ul>'
		},
		{ 
			'name':'SunGard',
			'logo':'SunGard.jpg',
			'industry': ['金融服務'], 
			'product': ['Windows', 'SQL Server'],
			'contact':'',
			'phone': '',
			'email': '',
			'website': 'www.sungard.com',
			'description': '<ul><li>SunGard金融解決方案為金融服務行業的每個部門，提供關鍵性軟件及IT服務。</li><li>為Windows 8而設的IntelliMatch營運監控解決方案，有助提升營運效率及企業在對帳處理時的表現。IntelliMatch營運監控-制解決方案為多功能的應用程式，不僅價格相宜，更加強Windows 8的保安功能，以便應付日後需求增加的連接及對帳處理。</li><li>SunGard Front Arena是專為電子交易及市場決策而設的金融解決方案，能於多個地方提供自動監管報價。透過Windows Server 2008 R2，解決方案可直接連結到電子交易所，並提供實時報價，只有低於毫秒的延誤。</li></ul><br /><strong>所部署的MS技術</strong><ul><li>Windows 8</li><li>SQL Server 2008 R2</li><li>SQL Server 2012</li></ul>'
		},
		{ 
			'name':'TFI Digital Media Limited',
			'logo':'TFI.jpg',
			'industry': ['傳媒娛樂'], 
			'product': ['Microsoft Azure', 'SQL Server', 'Windows', 'Xbox'],
			'contact':'W. H. SOON',
			'phone': '(852) 3755-1007',
			'email': 'soon@tfidm.com',
			'website': 'www.PoweredByHERMES.com',
			'description': '<strong>HERMES於以下6個核心範疇提供一站式視頻解決方案服務:</strong><ul><li>視頻編碼</li><li>內容管理</li><li>媒體串流及分發</li> <li>廣告系統</li><li>大數據分析</li><li>市場營銷</li></ul><br /><strong>所部署的 Microsoft 技術</strong><ul><li>Microsoft Windows Azure<sup>&reg;</sup>以雲端為基礎的視頻解決方案平台</li><li>Microsoft Windows Azure<sup>&reg;</sup>以雲端為基礎的機器學習</li><li>Microsoft PlayReady<sup>&reg;</sup> DRM</li></ul><br /><strong>目標客戶規模</strong><ul><li>可擴展的視頻串流，並由一用戶分發到數百萬用戶</li><li>目標為多平台及多屏幕　(任何電腦、手提電話/平板電腦、智能電視、電視盒、遊戲機、影院屏幕等等)</li><li>以特定HERMES 模塊，提供專業服務，建立個性化解決方案</li></ul>'
		},
		{ 
			'name':'紫光軟件(國際)有限公司',
			'logo':'unissoft.jpg',
			'industry': ['金融服務'], 
			'product': ['Microsoft Azure'],
			'contact':'Aldous Ng',
			'phone': '',
			'email': 'aldous_ng@unis-vitova.com',
			'website': '',
			'description': '<strong>TH-DOC.COM （雲檔）</strong><ul><li>首個為中小企而設，以雲端為基礎的電子記錄儲存系統或電子化檔案儲存系统</li><li>適用於大部份MFP設備作文件採集，支援靈活的圖像處理，更可輕鬆地進行重新掃描、旋轉、重新排序和刪除分頁。</li> <li>提供一個單一入口點，自動變換成不同分流的表格和文件，如電子郵件，NAS數據，ERP集成等。</li><li>文件庫擁有先進的用戶權限，允許用戶透過指定用戶或群組的訪問權限去建立、查看、編輯、導出、打印及刪除每款文件類型。</li><li>為用戶或群組使用的文件夾、文件級別和文件類型級別提供靈活的訪問控制。</li><li>支援複合文件及允許用戶將多個文件附加到單個TH-DOC文件紀錄。</li><li>提供一個安全的XPS檢視器來查看文件而毋須執行原生應用程式。檢視器可控制文件的列印、儲存和屏幕截圖。</li> <li>支援交叉參考連接器，用戶可透過連接器把各種文件連接起來方便參考，從而提升文件搜索和檢索的效率。</li><li>提供審計追踪功能，同時精確記錄終端用戶和管理員的操作。管理員可以查看和總結用戶在某指定時段的操作。</li></ul><br /><strong>所部署的MS技術</strong><br /><ul><li>.NET</li><li>Microsoft Azure</li></ul><br /><strong>目標客戶規模</strong><br /><ul><li>SMEs </li><li>中小企至中型公司</li></ul><br /><strong>所部署的MS技術</strong><br /><ul><li>ASM科技香港有限公司</li><li>創科實業有限公司</li><li>中信國際電訊（信息技術）有限公司</li><li>偉志電子(香港)有限公司</li><li>Certis Technology (HK) Limited</li><li>屈臣氏中國集團</li></ul>'
		}
	];