var db_product = [
        { 
			'name':'2016微软技术大会',
			'contenttype': 'article',
			'logo':'event_tech_kv_236x144.jpg',
			'banner':'event_tech_kv_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'',
			'eventtime':'',
			'expirydate':'2016-11-16T23:59:00+08:00',
			'location':'北京',
			'eventfor': ['IT专业人员', '开发人员'],
			'eventtype': ['研讨会及会议'],
			'category': ['线下会议'],
			'product': ['All'],
			'description': '<p>2016微软技术大会全新开启，携数字的力量蓄势发力，让您把握新的科技大势，与全球顶级技术专家面对面探讨最前沿的数字技术，探索数字化的无限潜能，动手体验获得更多灵感并得以将其付诸行动，尽情感受微软最新科技的魅力。</p><p>十二大精彩课程主题包含一百余场微软重量级课程，让您可以零距离体验到微软的最新技术及解决方案，尽情感受微软科技的魅力。</p>',
			'regurl':[{'regname':'观看视频','reglink':'https://www.microsoft.com/china/ignite/2016/'}],
			'gallery': ['']
		},
		{ 
			'name':'微软面向未来的创新学校网络在线研讨会',
			'contenttype': 'article',
			'logo':'future_seminar_236x144.jpg',
			'banner':'future_seminar_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'',
			'eventtime':'',
			'expirydate':'2016-11-16T23:59:00+08:00',
			'location':'在线会议',
			'eventfor': ['业务管理者','IT管理者'],
			'eventtype': ['在线会议回放'],
			'category': ['网络研讨会'],
			'product': ['All'],
			'description': '<p>简单的硬件堆砌、生硬的工作流程、枯燥的教学方式......教育领域中所面临的一系列问题都在周而复始地“上演”着。毫无乐趣的“疲态”教学使“教学相长”愈走愈远。</p><p>善于发现并解决问题的微软决不允许“恶性循环”就这样摆在面前。为倡导《教育信息化“十三五”规划》，更为了解放传统教育系统的“裹脚布”，微软在全球范围内创办了面向未来的创新学校。从应用层、系统层到物理层；从硬件配置到软件培训，微软创新学校提供了完整专业的解决方案，大力推动了教育领域的转型与升级。</p>',
			'regurl':[{'regname':'注册观看视频回放','reglink':'http://e.vhall.com/360061992?&refer=pc'}],
			'gallery': ['']
		},
		{ 
			'name':'Office 365云应用创新教学网络在线研讨会',
			'contenttype': 'article',
			'logo':'office_seminar_236x144.jpg',
			'banner':'office_seminar_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'',
			'eventtime':'',
			'expirydate':'2016-11-16T23:59:00+08:00',
			'location':'在线会议',
			'eventfor': ['业务管理者','IT管理者'],
			'eventtype': ['在线会议回放'],
			'category': ['网络研讨会'],
			'product': ['All'],
			'description': '<p>在这新型的信息化时代中，微软凭借其庞大且完善的教育产品体系，为客户提供了专业的服务与方案。Office 365 教育版是微软为教育机构打造的一整套教育云服务，它不仅包含最新版的 Office 软件，同时还能满足教育机构在沟通时的邮件处理和日程安排 （Exchange Online ) ，跨地域的教学信息共享（SharePoint Online），即时消息和在线可视网络教学课堂（Skype for Business）的需求。Office 365 教育版云服务将帮助教育机构实现教学的运维、管理和使用体验的革新，为教育机构带来更灵活、高效、更安全可靠的云教育办公方式。</p>',
			'regurl':[{'regname':'注册观看视频回放','reglink':'http://e.vhall.com/746416732?&refer=pc'}],
			'gallery': ['']
		},
		{ 
			'name':'【微软数字化教育创新体验营】广阔天地，无限探索 - Minecraft 以游戏方式创新教学',
			'contenttype': 'article',
			'logo':'numbers talk_236x144.jpg',
			'banner':'numbers talk_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'',
			'eventtime':'',
			'expirydate':'2016-11-16T23:59:00+08:00',
			'location':'在线会议',
			'eventfor': ['业务管理者','IT管理者'],
			'eventtype': ['解决方案演示'],
			'category': ['网络研讨会'],
			'product': ['All'],
			'description': '<p>Minecraft（我的世界）最初作为一款游戏，一经推出就以独特的「像素化」风格吸引了广大玩家的注意。在被微软收购后发展到今天，扩展性极高的「我的世界」已经不仅仅是一款游戏，在Minecraft的广阔天地中，用户只需要发挥自己想象力，就能将自己的梦想一点一点地实现。也正是被这样的特性吸引，越来越多的学校和教育机构开始考虑将其用在自己的数字化教学场景中。引人入胜的沉浸式体验，吸引了不同年龄段的学生不断尝试和自我完善，通过解决「实际问题」的过程学习经验和方法：<br />· 新颖的「学习方式」更能吸引学生注意力，大家可以在同一个虚拟空间中更自如地合作，挥洒创意。<br />· 通过寓教于乐的方式培养学生沟通交流、配合协作、批判性思维、创新精神，以及计算机化的思维方式。<br />· 完善的引导和定制功能，教师可以根据教学需求灵活定制一个供学生探索的世界，并能通过各种Mod和扩展获得更丰富的功能<br />· 根据研究，通过这种模拟方式的游戏和学习，学生的平均成绩提高了12%。</p>',
			'regurl':[{'regname':'注册观看视频回放','reglink':'http://msgovsolution.anruichina.com/edu/Home/Video'}],
			'gallery': ['']
		},{ 
			'name':'Annual CXO Summit',
			'contenttype': 'article',
			'logo':'CXO Summit_236x144.jpg',
			'banner':'CXO Summit_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年4月10日',
			'eventtime':'',
			'expirydate':'2017-04-10T23:59:00+08:00',
			'location':'北京',
			'eventfor': ['CXO Leadership'],
			'eventtype': ['研讨会及会议'],
			'category': ['线下会议'],
			'product': ['All'],
			'description': '<p>Today, every business is to some degree a digital business. But effective digital businesses, according to Gartner, are the ones that blend the digital and physical worlds in new ways to gain business advantage—for example, to boost productivity, enhance products, create new services, and provide better customer service. Digital is about the convergence of people, business, and things that disrupt existing business models. With this in mind, we are delighted to invite you to our exclusive Annual CXO Summit to be held in Beijing on April 10th. This event is organized by Avanade in partnership with Microsoft. This year’s theme is: Moving to the new world by driving digital, cloud transformation and next generation of UCC.</p>',
			'regurl':[''],
			'gallery': ['']
		},
		{ 
			'name':'FY17 微软数字化转型在线研讨会',
			'contenttype': 'article',
			'logo':'numbers talk_236x144.jpg',
			'banner':'numbers talk_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年5月11日',
			'eventtime':'',
			'expirydate':'2017-05-11T23:59:00+08:00',
			'location':'在线会议',
			'eventfor': ['IT专业人员','技术管理者'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': ['Internet of Things'],
			'description': '<p>创新谈何容易？新领域、新市场、新产品、新方向，每个“新”的背后都蕴藏着大量技术挑战等着我们来征服。微软诚邀您参加“工业4.0之物联网解决方案在线研讨会”，物联网和制造业服务化迎来了以智能制造为主导的第四次工业革命，即“工业4.0”。我们用数据说话，数百万IoT资产轻松链接并管理，助力单一客户近2000个数字营销项目，10分钟内成功搭建不同配置的开放测试环境。这些都是微软云计算和大数据技术将在工业4.0时代大展身手的实例。</p>',
			'regurl':[{'regname':'报名即将开始','reglink':'#'}],
			'gallery': ['']
		},{ 
			'name':'FY17 微软数字化转型在线研讨会',
			'contenttype': 'article',
			'logo':'numbers talk_236x144.jpg',
			'banner':'numbers talk_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年5月25日',
			'eventtime':'',
			'expirydate':'2017-05-25T23:59:00+08:00',
			'location':'在线会议',
			'eventfor': ['IT专业人员','技术管理者'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': ['Office', 'Sharepoint', 'Skype', 'Exchange'],
			'description': '<p>Office365作为最佳生产力和高效协同云服务应用平台的相关功能及解决方案，让您可以跨平台，跨设备实现完整的办公体验；拥有O365，您可以体验云端共享和协作的SharPoint Online,构建即时沟通和交互式网络会议的Skype for Business Online, 以及拥有超大邮箱、日程和任务管理的Exchange Online等。为了让大家更进一步深入了解O365，本次活动，我们讲阐述和demo有关O365在线部署，离线部署的内容。包括全新的Click-to-Run安全方式以及Telemetry管理工具，帮助IT人员了解如何利用Office 365引入的全新安装及管理功能，来提高管理效率，降低开销。</p>',
			'regurl':[{'regname':'报名即将开始','reglink':'#'}],
			'gallery': ['']
		},{ 
			'name':'FY17 微软数字化转型在线研讨会',
			'contenttype': 'article',
			'logo':'numbers talk_236x144.jpg',
			'banner':'numbers talk_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年6月8日',
			'eventtime':'',
			'expirydate':'2017-06-08T23:59:00+08:00',
			'location':'在线会议',
			'eventfor': ['IT专业人员','技术管理者'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': ['Power BI'],
			'description': '<p>在商业智能时代，数据分析及可视化变得日益重要。为了简化客户分析数据的工作，微软推出了用于分析数据和分享见解的一套业务分析工具——Power BI. 利用每台设备上提供的丰富的仪表板监视业务并快速获取答案。借助Microsoft Power BI, 您可以通过自由拖放画布并借助海量的现代数据可视化对象，直观地浏览数据。更值得期待的是它简单易操作的报告创作体验，在5分钟内，即可使用自然语言创建个性化的仪表板和数据报告。 下载Power BI APP, 您还可以实时地、以交互方式访问您的重要业务信息，享受移动办公的便捷。</p>',
			'regurl':[{'regname':'报名即将开始','reglink':'#'}],
			'gallery': ['']
		},{ 
			'name':'FY17 微软数字化转型在线研讨会',
			'contenttype': 'article',
			'logo':'numbers talk_236x144.jpg',
			'banner':'numbers talk_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年6月22日',
			'eventtime':'',
			'expirydate':'2017-06-22T23:59:00+08:00',
			'location':'在线会议',
			'eventfor': ['IT专业人员','技术管理者'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Azure'],
			'description': '<p>在人工智能方面，微软在公有云Azure上推出了一项基于Web使用的机器学习服务工具——Azure Machine Learning(简称“AML”)，它可以实现借助算法让电脑对大量流动数据进行识别。您只需上传数据，利用机器学习模块提供的一些算法接口和R语言或其他语言接口，就能利用Microsoft Azure强大的云计算能力来实现自己的机器学习的任务，充分使用机器的“智慧”。</p>',
			'regurl':[{'regname':'报名即将开始','reglink':'#'}],
			'gallery': ['']
		},{ 
			'name':'FY17 Cloud CIE企业通用情景体验活动',
			'contenttype': 'article',
			'logo':'FY17_CloudIE_236x144.jpg',
			'banner':'FY17_CloudIE_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年5月18日',
			'eventtime':'',
			'expirydate':'2017-05-18T23:59:00+08:00',
			'location':'上海',
			'eventfor': ['IT专业人员'],
			'eventtype': ['研讨会及会议'],
			'category': ['线下会议'],
			'product': ['Office', 'Sharepoint', 'Skype', 'Exchange'],
			'description': '<p>微软企业生产力高效体验之旅（Customer Immersion Experience）是微软专为全球重要客户所设计，构架在Microsoft 业务生产力产品及Office 365云应用平台，以实际企业应用案例为情景、通过真实体验的交互式环境让企业用户深入了解微软新一代生产力架构平台所带来的企业价值，包括：统一沟通（Unified Communications）、协同工作 （Collaboration）、企业内容管理 （Enterprise Content Management）、企业社交（Enterprise Social）、企业项目管理（Enterprise Project Management）、商务智能（Business Intelligence）等当红议题。 </p><p>本次研讨会以“企业通用情景体验”为主题，诚邀您拔冗莅临，与微软专家和行业精英深入探讨如何利用微软产品和创新技术，帮助企业在激烈的竞争中立于不败之地。 如您对此次活动感兴趣，请联系：<a href="mailto:v-jiwen@microsoft.com">v-jiwen@microsoft.com</a>.  </p>',
			'regurl':[{'regname':'立即报名','reglink':'http://t.cn/RXajlVc'}],
			'gallery': ['']
		},{ 
			'name':'公有云架构师培训 - 北京站',
			'contenttype': 'article',
			'logo':'cloundtraining_236x144.jpg',
			'banner':'cloundtraining_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年2月21日至<br />2017年2月22日',
			'eventtime':'',
			'expirydate':'2017-02-22T23:59:00+08:00',
			'location':'北京',
			'eventfor': ['新客戶'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Microsoft Azure'],
			'description': '<p>随着技术的成熟与发展，云计算已经或正在改变着整个IT产业。云计算市场逐渐从提供产品向提供服务转型。作为微软最重要的战略转型服务之一，历经过去数年的快速演变，使用微软技术由世纪互联运营的 Microsoft Azure已经成为了各企业面向“互联网+”转型趋势中的最佳公有云合作伙伴与服务提供商。针对多样化的应用场景，无论是需要混合云支持的传统企业应用，还是面向新一代物联网应用的存储和计算需求，或者后台大数据的分析运用， Microsoft Azure 都提供了全面的解决方案与技术支持。<br />我们将在两天的时间里为您介绍更多 Microsoft Azure 的功能，帮助您从计算服务、数据服务、应用服务和网络服务中全方位的了解 Microsoft Azure。</p>',
			'regurl':[''],
			'gallery': ['']
		},{ 
			'name':'公有云架构师培训 - 上海站',
			'contenttype': 'article',
			'logo':'cloundtraining_236x144.jpg',
			'banner':'cloundtraining_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年3月16日至<br />2017年3月17日',
			'eventtime':'',
			'expirydate':'2017-03-17T23:59:00+08:00',
			'location':'上海',
			'eventfor': ['新客戶'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Microsoft Azure'],
			'description': '<p>随着技术的成熟与发展，云计算已经或正在改变着整个IT产业。云计算市场逐渐从提供产品向提供服务转型。作为微软最重要的战略转型服务之一，历经过去数年的快速演变，使用微软技术由世纪互联运营的 Microsoft Azure已经成为了各企业面向“互联网+”转型趋势中的最佳公有云合作伙伴与服务提供商。针对多样化的应用场景，无论是需要混合云支持的传统企业应用，还是面向新一代物联网应用的存储和计算需求，或者后台大数据的分析运用， Microsoft Azure 都提供了全面的解决方案与技术支持。<br />我们将在两天的时间里为您介绍更多 Microsoft Azure 的功能，帮助您从计算服务、数据服务、应用服务和网络服务中全方位的了解 Microsoft Azure。</p>',
			'regurl':[''],
			'gallery': ['']
		},{ 
			'name':'公有云架构师培训 - 上海站',
			'contenttype': 'article',
			'logo':'cloundtraining_236x144.jpg',
			'banner':'cloundtraining_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年5月10日至<br />2017年5月11日',
			'eventtime':'',
			'expirydate':'2017-05-11T23:59:00+08:00',
			'location':'上海',
			'eventfor': ['新客戶'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Microsoft Azure'],
			'description': '<p>随着技术的成熟与发展，云计算已经或正在改变着整个IT产业。云计算市场逐渐从提供产品向提供服务转型。作为微软最重要的战略转型服务之一，历经过去数年的快速演变，使用微软技术由世纪互联运营的 Microsoft Azure已经成为了各企业面向“互联网+”转型趋势中的最佳公有云合作伙伴与服务提供商。针对多样化的应用场景，无论是需要混合云支持的传统企业应用，还是面向新一代物联网应用的存储和计算需求，或者后台大数据的分析运用， Microsoft Azure 都提供了全面的解决方案与技术支持。<br />我们将在两天的时间里为您介绍更多 Microsoft Azure 的功能，帮助您从计算服务、数据服务、应用服务和网络服务中全方位的了解 Microsoft Azure。</p>',
			'regurl':[{'regname':'立即报名','reglink':'http://a.wmccg.cn/microsoft/170412/reg.asp'}],
			'gallery': ['']
		},{ 
			'name':'公有云架构师培训 - 北京站',
			'contenttype': 'article',
			'logo':'cloundtraining_236x144.jpg',
			'banner':'cloundtraining_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年5月17日至<br />2017年5月18日',
			'eventtime':'',
			'expirydate':'2017-05-18T23:59:00+08:00',
			'location':'北京',
			'eventfor': ['新客戶'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Microsoft Azure'],
			'description': '<p>随着技术的成熟与发展，云计算已经或正在改变着整个IT产业。云计算市场逐渐从提供产品向提供服务转型。作为微软最重要的战略转型服务之一，历经过去数年的快速演变，使用微软技术由世纪互联运营的 Microsoft Azure已经成为了各企业面向“互联网+”转型趋势中的最佳公有云合作伙伴与服务提供商。针对多样化的应用场景，无论是需要混合云支持的传统企业应用，还是面向新一代物联网应用的存储和计算需求，或者后台大数据的分析运用， Microsoft Azure 都提供了全面的解决方案与技术支持。<br />我们将在两天的时间里为您介绍更多 Microsoft Azure 的功能，帮助您从计算服务、数据服务、应用服务和网络服务中全方位的了解 Microsoft Azure。</p>',
			'regurl':[{'regname':'立即报名','reglink':'http://a.wmccg.cn/microsoft/170412/reg.asp'}],
			'gallery': ['']
		},{ 
			'name':'公有云架构师培训 - 深圳站',
			'contenttype': 'article',
			'logo':'cloundtraining_236x144.jpg',
			'banner':'cloundtraining_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年6月8日至<br />2017年6月9日',
			'eventtime':'',
			'expirydate':'2017-06-09T23:59:00+08:00',
			'location':'深圳',
			'eventfor': ['新客戶'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Microsoft Azure'],
			'description': '<p>随着技术的成熟与发展，云计算已经或正在改变着整个IT产业。云计算市场逐渐从提供产品向提供服务转型。作为微软最重要的战略转型服务之一，历经过去数年的快速演变，使用微软技术由世纪互联运营的 Microsoft Azure已经成为了各企业面向“互联网+”转型趋势中的最佳公有云合作伙伴与服务提供商。针对多样化的应用场景，无论是需要混合云支持的传统企业应用，还是面向新一代物联网应用的存储和计算需求，或者后台大数据的分析运用， Microsoft Azure 都提供了全面的解决方案与技术支持。<br />我们将在两天的时间里为您介绍更多 Microsoft Azure 的功能，帮助您从计算服务、数据服务、应用服务和网络服务中全方位的了解 Microsoft Azure。</p>',
			'regurl':[{'regname':'立即报名','reglink':'http://a.wmccg.cn/microsoft/170412/reg.asp'}],
			'gallery': ['']
		},{ 
			'name':'Azure在线培训/Azure Webinar',
			'contenttype': 'article',
			'logo':'Azure_course_236x144.jpg',
			'banner':'Azure_course_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年2月22日',
			'eventtime':'',
			'expirydate':'2017-02-22T23:59:00+08:00',
			'location':'在线培训',
			'eventfor': ['Azure客戶'],
			'eventtype': ['技术培训'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Azure'],
			'description': '<p>本次课程将分为批处理和数据工厂 2 部分。<br />批处理部分将详细介绍如何通过批处理帮助用户在云中有效运行大规模并行的高性能计算 (HPC) 应用程序。通过实际案例演示如何根据需要或计划运行作业，而不需动手创建、配置HPC群集、各个虚拟机和任务计划基础架构。<br />数据工厂部分将介绍使用数据工厂如何轻松采集多个本地或云数据源数据，然后连接到具有数据管理网关的本地数据源，进行应用预处理，最终使用数据管道将原始数据转换为应用程序使用的完成数据或成型数据。 </p>',
			'regurl':[{'regname':'批处理','reglink':'http://www.azure.cn/webinars/detail/29'}, {'regname':'数据工厂','reglink':'http://www.azure.cn/webinars/detail/30'}],
			'gallery': ['']
		},{ 
			'name':'Azure在线培训/Azure Webinar',
			'contenttype': 'article',
			'logo':'Azure_course_236x144.jpg',
			'banner':'Azure_course_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年2月24日',
			'eventtime':'',
			'expirydate':'2017-02-24T23:59:00+08:00',
			'location':'在线培训',
			'eventfor': ['Azure客戶'],
			'eventtype': ['技术培训'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Azure'],
			'description': '<p>本次课程包括虚拟网络和 Redis 缓存两部分。<br />主要为大家讲解如何通过虚拟网络实现站点到站点 VPN 轻松扩展到本地网络；利用 Redis 缓存实现高吞吐量、低延迟数据访问。</p>',
			'regurl':[{'regname':'流量管理器','reglink':'http://www.azure.cn/webinars/detail/31'}, {'regname':'虚拟网络','reglink':'http://www.azure.cn/webinars/detail/32'}],
			'gallery': ['']
		},{ 
			'name':'Azure在线培训/Azure Webinar',
			'contenttype': 'article',
			'logo':'Azure_course_236x144.jpg',
			'banner':'Azure_course_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年3月8日',
			'eventtime':'',
			'expirydate':'2017-03-08T23:59:00+08:00',
			'location':'在线培训',
			'eventfor': ['Azure客戶'],
			'eventtype': ['技术培训'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Azure'],
			'description': '<p>Azure 容器服务让创建、配置和管理预配置来运行容器化应用程序的虚拟机群集变得更简单。旨在通过使用当今客户中热门的开源工具和技术提供容器托管环境。本次课程将详细介绍如何使用热门开源计划和业务流程工具的优化配置，部署应用程序。</p>',
			'regurl':[{'regname':'Azure 容器服务','reglink':'http://www.azure.cn/webinars/detail/33'}],
			'gallery': ['']
		},{ 
			'name':'Azure在线培训/Azure Webinar',
			'contenttype': 'article',
			'logo':'Azure_course_236x144.jpg',
			'banner':'Azure_course_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年3月15日',
			'eventtime':'',
			'expirydate':'2017-03-15T23:59:00+08:00',
			'location':'在线培训',
			'eventfor': ['Azure客戶'],
			'eventtype': ['技术培训'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Azure'],
			'description': '<p>本次课程将分为服务总结和备份 2 部分。<br />服务总线部分将介绍如何实现应用程序之间如何进行消息传递。现场演示如何管理云中的消息传递，将本地部署应用程序连接到云端。<br />备份部分将介绍如何基于云的备份简单可靠地将服务器备份到云端。</p>',
			'regurl':[{'regname':'服务总线','reglink':'http://www.azure.cn/webinars/detail/38'}, {'regname':'备份','reglink':'http://www.azure.cn/webinars/detail/39'}],
			'gallery': ['']
		},{ 
			'name':'Azure在线培训/Azure Webinar',
			'contenttype': 'article',
			'logo':'Azure_course_236x144.jpg',
			'banner':'Azure_course_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年3月22日',
			'eventtime':'',
			'expirydate':'2017-03-22T23:59:00+08:00',
			'location':'在线培训',
			'eventfor': ['Azure客戶'],
			'eventtype': ['技术培训'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Azure'],
			'description': '<p>在本课程中，我们将介绍3部分内容。<br />Data Lake存储：介绍 HDInsight 不同类型集群的架构和微软对 Hadoop 的改进。展示如何在 Azure 上快速配置 HDInsight 集群和提交基于 Spark 的大数据批处理请求。<br />StorSimple：如何通过混合云存储解决方案为企业降低成本，确保在不中断数据中心日常操作的情况下，可靠快速的灾难恢复，增强 IT 灵活性，推动业务智能和决策。<br />秘钥保管库：介绍如何通过存储在密钥保管库中的密钥对其他密钥，以及类似密码这样的密文进行加密。在几分钟内预配新的保管库和密钥，可集中管理密钥、密文密码和策略。</p>',
			'regurl':[{'regname':'StorSimple','reglink':'http://www.azure.cn/webinars/detail/36'}, {'regname':'密钥保管库','reglink':'http://www.azure.cn/webinars/detail/37'}],
			'gallery': ['']
		},{ 
			'name':'Azure在线培训/Azure Webinar',
			'contenttype': 'article',
			'logo':'Azure_course_236x144.jpg',
			'banner':'Azure_course_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年4月12日',
			'eventtime':'',
			'expirydate':'2017-04-12T23:59:00+08:00',
			'location':'在线培训',
			'eventfor': ['Azure客戶'],
			'eventtype': ['技术培训'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Azure'],
			'description': '<p>API 管理，是将 API 发布到外部和内部消费者的统包式解决方案。本次在线课程将介绍API 管理的主要功能和架构，另外演示如何配置一个简单的API和产品。</p>',
			'regurl':[''],
			'gallery': ['']
		},{ 
			'name':'Azure在线培训/Azure Webinar',
			'contenttype': 'article',
			'logo':'Azure_course_236x144.jpg',
			'banner':'Azure_course_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年4月19日',
			'eventtime':'',
			'expirydate':'2017-04-19T23:59:00+08:00',
			'location':'在线培训',
			'eventfor': ['Azure客戶'],
			'eventtype': ['技术培训'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Azure'],
			'description': '<p>自动化在线课程将介绍如何使用流程自动化来简化云管理，消除耗时的重复性任务，提高可靠性和效率。</p>',
			'regurl':[''],
			'gallery': ['']
		},{ 
			'name':'Azure在线培训/Azure Webinar',
			'contenttype': 'article',
			'logo':'Azure_course_236x144.jpg',
			'banner':'Azure_course_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年4月26日',
			'eventtime':'',
			'expirydate':'2017-04-26T23:59:00+08:00',
			'location':'在线培训',
			'eventfor': ['Azure客戶'],
			'eventtype': ['技术培训'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Azure'],
			'description': '<p>本次在线课程介绍了云搜索服务是如何在 Web 和移动应用开发中应用，以及如何借助完全托管的服务减少复杂性。</p>',
			'regurl':[''],
			'gallery': ['']
		},{ 
			'name':'SQL Server Mission Critical workshop (Shanghai)',
			'contenttype': 'article',
			'logo':'SQL_workshop_236x144.jpg',
			'banner':'SQL_workshop_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年4月11日',
			'eventtime':'',
			'expirydate':'2017-04-11T23:59:00+08:00',
			'location':'上海',
			'eventfor': ['新客戶'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Server and Management'],
			'description': '<p>Microsoft SQL Server 2016 可提供突破性的 In-Memory 性能、无与伦比的安全性、端到端移动商业智能和高级分析功能，其强大的数据处理能力，扩展性和高可用性，足以承载企业级的关键应用程序。而SQL Server数据处理性能的优劣，直接影响到应用程序的用户体验。本次活动会向您深入介绍SQL Server的工作原理，性能的评估方法，常见的性能问题和调优手段，以及开发高性能T-SQL语句的最佳实践。更有机会现场与微软资深技术专家当面交流，解答您的相关疑问。</p>',
			'regurl':[''],
			'gallery': ['']
		},{ 
			'name':'SQL Server Mission Critical workshop (Guangzhou)',
			'contenttype': 'article',
			'logo':'SQL_workshop_236x144.jpg',
			'banner':'SQL_workshop_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年4月19日',
			'eventtime':'',
			'expirydate':'2017-04-19T23:59:00+08:00',
			'location':'广州',
			'eventfor': ['新客戶'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Server and Management'],
			'description': '<p>Microsoft SQL Server 2016 可提供突破性的 In-Memory 性能、无与伦比的安全性、端到端移动商业智能和高级分析功能，其强大的数据处理能力，扩展性和高可用性，足以承载企业级的关键应用程序。而SQL Server数据处理性能的优劣，直接影响到应用程序的用户体验。本次活动会向您深入介绍SQL Server的工作原理，性能的评估方法，常见的性能问题和调优手段，以及开发高性能T-SQL语句的最佳实践。更有机会现场与微软资深技术专家当面交流，解答您的相关疑问。</p>',
			'regurl':[''],
			'gallery': ['']
		},{ 
			'name':'SQL Server Mission Critical workshop (Beijing)',
			'contenttype': 'article',
			'logo':'SQL_workshop_236x144.jpg',
			'banner':'SQL_workshop_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年4月28日',
			'eventtime':'',
			'expirydate':'2017-04-28T23:59:00+08:00',
			'location':'北京',
			'eventfor': ['新客戶'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Server and Management'],
			'description': '<p>Microsoft SQL Server 2016 可提供突破性的 In-Memory 性能、无与伦比的安全性、端到端移动商业智能和高级分析功能，其强大的数据处理能力，扩展性和高可用性，足以承载企业级的关键应用程序。而SQL Server数据处理性能的优劣，直接影响到应用程序的用户体验。本次活动会向您深入介绍SQL Server的工作原理，性能的评估方法，常见的性能问题和调优手段，以及开发高性能T-SQL语句的最佳实践。更有机会现场与微软资深技术专家当面交流，解答您的相关疑问。</p>',
			'regurl':[{'regname':'立即报名','reglink':'http://t.cn/RXa0hLM'}],
			'gallery': ['']
		},{ 
			'name':'Go Global Campaign',
			'contenttype': 'article',
			'logo':'sailing seminar_236x144.jpg',
			'banner':'sailing seminar_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年3月14日',
			'eventtime':'',
			'expirydate':'2017-03-14T23:59:00+08:00',
			'location':'杭州',
			'eventfor': ['Azure客戶', '新客戶'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Microsoft Azure'],
			'description': '<p>Microsoft Go Global Program 协助中国国内用户运用国际版Azure的丰富功能来服务更多国内与国际用户。透过丰富的人工智能、数据分析、跨平台应用开发等PaaS或SaaS功能，部署您的应用在全球34个区域的数据中心，服务贵公司在世界各地的用户，且提升运维效率，优化使用者体验！</p>',
			'regurl':[''],
			'gallery': [{'s':'go campaign 0314_1_143x87.jpg', 'l':'go campaign 0314_1_950x530.jpg'},{'s':'go campaign 0314_2_143x87.jpg', 'l':'go campaign 0314_2_950x530.jpg'},{'s':'go campaign 0314_3_143x87.jpg', 'l':'go campaign 0314_3_950x530.jpg'},{'s':'go campaign 0314_4_143x87.jpg', 'l':'go campaign 0314_4_950x530.jpg'}]
		},{ 
			'name':'Go Global Campaign',
			'contenttype': 'article',
			'logo':'sailing seminar_236x144.jpg',
			'banner':'sailing seminar_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年3月15日',
			'eventtime':'',
			'expirydate':'2017-03-15T23:59:00+08:00',
			'location':'深圳',
			'eventfor': ['Azure客戶', '新客戶'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Microsoft Azure'],
			'description': '<p>Microsoft Go Global Program 协助中国国内用户运用国际版Azure的丰富功能来服务更多国内与国际用户。透过丰富的人工智能、数据分析、跨平台应用开发等PaaS或SaaS功能，部署您的应用在全球34个区域的数据中心，服务贵公司在世界各地的用户，且提升运维效率，优化使用者体验！</p>',
			'regurl':[''],
			'gallery': [{'s':'go campaign 0315_1_143x87.jpg', 'l':'go campaign 0315_1_950x530.jpg'},{'s':'go campaign 0315_2_143x87.jpg', 'l':'go campaign 0315_2_950x530.jpg'},{'s':'go campaign 0315_3_143x87.jpg', 'l':'go campaign 0315_3_950x530.jpg'},{'s':'go campaign 0315_4_143x87.jpg', 'l':'go campaign 0315_4_950x530.jpg'}]
		},{ 
			'name':'Go Global Campaign',
			'contenttype': 'article',
			'logo':'sailing seminar_236x144.jpg',
			'banner':'sailing seminar_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年3月16日',
			'eventtime':'',
			'expirydate':'2017-03-16T23:59:00+08:00',
			'location':'成都',
			'eventfor': ['Azure客戶', '新客戶'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Microsoft Azure'],
			'description': '<p>Microsoft Go Global Program 协助中国国内用户运用国际版Azure的丰富功能来服务更多国内与国际用户。透过丰富的人工智能、数据分析、跨平台应用开发等PaaS或SaaS功能，部署您的应用在全球34个区域的数据中心，服务贵公司在世界各地的用户，且提升运维效率，优化使用者体验！</p>',
			'regurl':[''],
			'gallery': [{'s':'go campaign 0316_1_143x87.jpg', 'l':'go campaign 0316_1_950x530.jpg'},{'s':'go campaign 0316_2_143x87.jpg', 'l':'go campaign 0316_2_950x530.jpg'},{'s':'go campaign 0316_3_143x87.jpg', 'l':'go campaign 0316_3_950x530.jpg'},{'s':'go campaign 0316_4_143x87.jpg', 'l':'go campaign 0316_4_950x530.jpg'}]
		},{ 
			'name':'Go Global Campaign',
			'contenttype': 'article',
			'logo':'sailing seminar_236x144.jpg',
			'banner':'sailing seminar_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年3月21日',
			'eventtime':'',
			'expirydate':'2017-03-21T23:59:00+08:00',
			'location':'北京',
			'eventfor': ['Azure客戶', '新客戶'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Microsoft Azure'],
			'description': '<p>Microsoft Go Global Program 协助中国国内用户运用国际版Azure的丰富功能来服务更多国内与国际用户。透过丰富的人工智能、数据分析、跨平台应用开发等PaaS或SaaS功能，部署您的应用在全球34个区域的数据中心，服务贵公司在世界各地的用户，且提升运维效率，优化使用者体验！</p>',
			'regurl':[''],
			'gallery': [{'s':'go campaign 0321_1_143x87.jpg', 'l':'go campaign 0321_1_950x530.jpg'},{'s':'go campaign 0321_2_143x87.jpg', 'l':'go campaign 0321_2_950x530.jpg'},{'s':'go campaign 0321_3_143x87.jpg', 'l':'go campaign 0321_3_950x530.jpg'},{'s':'go campaign 0321_4_143x87.jpg', 'l':'go campaign 0321_4_950x530.jpg'}]
		},{ 
			'name':'Go Global Campaign',
			'contenttype': 'article',
			'logo':'sailing seminar_236x144.jpg',
			'banner':'sailing seminar_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年3月22日',
			'eventtime':'',
			'expirydate':'2017-03-22T23:59:00+08:00',
			'location':'厦门',
			'eventfor': ['Azure客戶', '新客戶'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Microsoft Azure'],
			'description': '<p>Microsoft Go Global Program 协助中国国内用户运用国际版Azure的丰富功能来服务更多国内与国际用户。透过丰富的人工智能、数据分析、跨平台应用开发等PaaS或SaaS功能，部署您的应用在全球34个区域的数据中心，服务贵公司在世界各地的用户，且提升运维效率，优化使用者体验！</p>',
			'regurl':[''],
			'gallery': [{'s':'go campaign 0322_1_143x87.jpg', 'l':'go campaign 0322_1_950x530.jpg'},{'s':'go campaign 0322_2_143x87.jpg', 'l':'go campaign 0322_2_950x530.jpg'},{'s':'go campaign 0322_3_143x87.jpg', 'l':'go campaign 0322_3_950x530.jpg'},{'s':'go campaign 0322_4_143x87.jpg', 'l':'go campaign 0322_4_950x530.jpg'}]
		},{ 
			'name':'Go Global Campaign',
			'contenttype': 'article',
			'logo':'sailing seminar_236x144.jpg',
			'banner':'sailing seminar_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年3月23日',
			'eventtime':'',
			'expirydate':'2017-03-23T23:59:00+08:00',
			'location':'上海',
			'eventfor': ['Azure客戶', '新客戶'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Microsoft Azure'],
			'description': '<p>Microsoft Go Global Program 协助中国国内用户运用国际版Azure的丰富功能来服务更多国内与国际用户。透过丰富的人工智能、数据分析、跨平台应用开发等PaaS或SaaS功能，部署您的应用在全球34个区域的数据中心，服务贵公司在世界各地的用户，且提升运维效率，优化使用者体验！</p>',
			'regurl':[''],
			'gallery': [{'s':'go campaign 0323_1_143x87.jpg', 'l':'go campaign 0323_1_950x530.jpg'},{'s':'go campaign 0323_2_143x87.jpg', 'l':'go campaign 0323_2_950x530.jpg'},{'s':'go campaign 0323_3_143x87.jpg', 'l':'go campaign 0323_3_950x530.jpg'},{'s':'go campaign 0323_4_143x87.jpg', 'l':'go campaign 0323_4_950x530.jpg'}]
		},{ 
			'name':'Go Global CAD Week Hands on Workshop-Shanghai',
			'contenttype': 'article',
			'logo':'cloud seminar_236x144.jpg',
			'banner':'cloud seminar_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年4月11日',
			'eventtime':'',
			'expirydate':'2017-04-11T23:59:00+08:00',
			'location':'上海',
			'eventfor': ['Azure客戶', '新客戶'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Microsoft Azure'],
			'description': '<p>Microsoft Go Global Program将携手微软企业服务专家团队共同为国内用户分享如何让用户快速的将应用服务和业务部署至全球Azure的案例，本次研讨会将在现场通过演示真实的场景来构建Azure上的web /移动应用程序，结合高层次的数据分析和CDN示例进行经验分享。除此之外，更有机会与微软资深技术专家现场交流，解答您的相关疑问。</p>',
			'regurl':[{'regname':'报名即将开始','reglink':'#'}],
			'gallery': ['']
		},{ 
			'name':'Go Global CAD Week Hands on Workshop-Shenzhen',
			'contenttype': 'article',
			'logo':'cloud seminar_236x144.jpg',
			'banner':'cloud seminar_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年4月12日',
			'eventtime':'',
			'expirydate':'2017-04-12T23:59:00+08:00',
			'location':'深圳',
			'eventfor': ['Azure客戶', '新客戶'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Microsoft Azure'],
			'description': '<p>Microsoft Go Global Program将携手微软企业服务专家团队共同为国内用户分享如何让用户快速的将应用服务和业务部署至全球Azure的案例，本次研讨会将在现场通过演示真实的场景来构建Azure上的web /移动应用程序，结合高层次的数据分析和CDN示例进行经验分享。除此之外，更有机会与微软资深技术专家现场交流，解答您的相关疑问。</p>',
			'regurl':[{'regname':'报名即将开始','reglink':'#'}],
			'gallery': ['']
		},{ 
			'name':'IoT Partner Workshop',
			'contenttype': 'article',
			'logo':'network corp_training_236x144.jpg',
			'banner':'network corp_training_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年2月24日',
			'eventtime':'',
			'expirydate':'2017-02-24T23:59:00+08:00',
			'location':'北京',
			'eventfor': ['合作伙伴'],
			'eventtype': ['技术培训'],
			'category': ['线下会议'],
			'product': ['Internet of Things'],
			'description': '<p>IoT partner workshop hosted in Beijing of 64 attendees with 33 partners. The partner workshop introduces latest Microsoft IoT roadmap, reference cases, and feature update.</p>',
			'regurl':[''],
			'gallery': [{'s':'IoT workshop_1_143x87.jpg', 'l':'IoT workshop_1_950x530.jpg'},{'s':'IoT workshop_2_143x87.jpg', 'l':'IoT workshop_2_950x530.jpg'},{'s':'IoT workshop_3_143x87.jpg', 'l':'IoT workshop_3_950x530.jpg'},{'s':'IoT workshop_4_143x87.jpg', 'l':'IoT workshop_4_950x530.jpg'}]
		},{ 
			'name':'三云开泰 云解决方案开放日',
			'contenttype': 'article',
			'logo':'cloud days_236x144.jpg',
			'banner':'cloud days_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年4月21日',
			'eventtime':'',
			'expirydate':'2017-04-21T23:59:00+08:00',
			'location':'在线会议',
			'eventfor': ['销售和市场专业人员','IT专业人员','开发人员','教育工作者','中小型企业经营者','业务管理者','IT管理者','CXO Leadership','技术管理者'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Dynamics'],
			'description': '<p>以Dynamics 365发布为先导，以Azure、Office 365登陆中国市场三周年为契机，微软三大云产品相聚合力，将在4月份开展声势浩大的「因云而聚 生态共赢」微软 Cloud Days 云开放日活动。参加此次活动，每一位销售都将在 Azure / Office / Dynamics BG 以及合作伙伴前所未有的支持力度下获得更强的云产品销售能力，以更多业绩达成助力微软打造世界一流云产品销售团队的目标！<br />本次活动要求全体销售人员参加，我们将通过培训学习、伙伴速配、视频认证、客户圆桌会议、Call Center Call-Down等环节，帮助锤炼云销售能力，与合作伙伴一起为客户提供适应数字化转型的云业务体验。<br />此外，活动还将隆重举行合作伙伴解决方案联展，MTC和Center One更是特别为本次活动提供了开放参观机会。良机难得，建议您及时通过附件中的邀请函邀请客户一起参加活动，促进赢单！</p>',
			'regurl':[{'regname':'了解更多','reglink':'http://www.microsoft.com/China/cloudproductivity/Dynamics365webnar.html'}],
			'gallery': ['']
		},{ 
			'name':'Dynamics 365 First look',
			'contenttype': 'article',
			'logo':'numerization_236x144.jpg',
			'banner':'numerization_630x234-01.jpg',
			'youtubeurl': '',
			'eventdate':'2017年5月12日',
			'eventtime':'',
			'expirydate':'2017-05-12T23:59:00+08:00',
			'location':'在线会议',
			'eventfor': ['销售和市场专业人员','IT专业人员','开发人员','教育工作者','中小型企业经营者','业务管理者','IT管理者','CXO Leadership','技术管理者'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Dynamics'],
			'description': '<p>微软Dynamics 365是基于云的端到端的智能业务应用平台，该平台将CRM和ERP整合于统一的云服务中，并将功能细化为多个应用， 近年来，经济不景气，中小型零售商意识到必须寻求具有创新性的竞争方式，同时针对不同区域的不同产品数量需求不一致，虽有大量数据却法有效从中准确分析出客户需求。各部门协作效率低,造成流程周期长,问题不能及时解决。Dynamics 365从您的需求开始，从正确适合您企业的规模开始，并在云中根据企业的成长节凑灵活调整，通过生产力工具对流程灵活定制来提高员工的能动性，引导员工在流程中利用智能引擎得出最佳结果，在灵活和高扩展的应用和平台上保持敏捷和可朔性的业务管理。</p>',
			'regurl':[{'regname':'立即报名','reglink':'https://www.microsoft.com/China/cloudproductivity/webinarreg.html?event=2'}],
			'gallery': ['']
		},{ 
			'name':'Dynamics 365 First look',
			'contenttype': 'article',
			'logo':'numerization_236x144.jpg',
			'banner':'numerization_630x234-01.jpg',
			'youtubeurl': '',
			'eventdate':'2017年5月19日',
			'eventtime':'',
			'expirydate':'2017-05-19T23:59:00+08:00',
			'location':'在线会议',
			'eventfor': ['销售和市场专业人员','IT专业人员','开发人员','教育工作者','中小型企业经营者','业务管理者','IT管理者','CXO Leadership','技术管理者'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Dynamics'],
			'description': '<p>微软Dynamics 365是基于云的端到端的智能业务应用平台，该平台将CRM和ERP整合于统一的云服务中，并将功能细化为多个应用， 近年来，经济不景气，中小型零售商意识到必须寻求具有创新性的竞争方式，同时针对不同区域的不同产品数量需求不一致，虽有大量数据却法有效从中准确分析出客户需求。各部门协作效率低,造成流程周期长,问题不能及时解决。Dynamics 365从您的需求开始，从正确适合您企业的规模开始，并在云中根据企业的成长节凑灵活调整，通过生产力工具对流程灵活定制来提高员工的能动性，引导员工在流程中利用智能引擎得出最佳结果，在灵活和高扩展的应用和平台上保持敏捷和可朔性的业务管理。</p>',
			'regurl':[{'regname':'报名即将开始','reglink':'http://www.microsoft.com/China/cloudproductivity/Dynamics365webnar.html'}],
			'gallery': ['']
		},{ 
			'name':'Dynamics 365 First look',
			'contenttype': 'article',
			'logo':'numerization_236x144.jpg',
			'banner':'numerization_630x234-01.jpg',
			'youtubeurl': '',
			'eventdate':'2017年5月26日',
			'eventtime':'',
			'expirydate':'2017-05-26T23:59:00+08:00',
			'location':'在线会议',
			'eventfor': ['销售和市场专业人员','IT专业人员','开发人员','教育工作者','中小型企业经营者','业务管理者','IT管理者','CXO Leadership','技术管理者'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Dynamics'],
			'description': '<p>微软Dynamics 365是基于云的端到端的智能业务应用平台，该平台将CRM和ERP整合于统一的云服务中，并将功能细化为多个应用， 近年来，经济不景气，中小型零售商意识到必须寻求具有创新性的竞争方式，同时针对不同区域的不同产品数量需求不一致，虽有大量数据却法有效从中准确分析出客户需求。各部门协作效率低,造成流程周期长,问题不能及时解决。Dynamics 365从您的需求开始，从正确适合您企业的规模开始，并在云中根据企业的成长节凑灵活调整，通过生产力工具对流程灵活定制来提高员工的能动性，引导员工在流程中利用智能引擎得出最佳结果，在灵活和高扩展的应用和平台上保持敏捷和可朔性的业务管理。</p>',
			'regurl':[{'regname':'报名即将开始','reglink':'http://www.microsoft.com/China/cloudproductivity/Dynamics365webnar.html'}],
			'gallery': ['']
		},{ 
			'name':'Dynamics 合作伙伴 嘉宾访谈室-Dynamics 365助力企业售后服务数字化转型',
			'contenttype': 'article',
			'logo':'guest_236x144.jpg',
			'banner':'guest_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年5月16日',
			'eventtime':'',
			'expirydate':'2017-05-16T23:59:00+08:00',
			'location':'在线会议',
			'eventfor': ['销售和市场专业人员','IT专业人员','开发人员','教育工作者','中小型企业经营者','业务管理者','IT管理者','CXO Leadership','技术管理者'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Dynamics'],
			'description': '<p>全渠道智能售后服务管理系统，帮助制造业企业建立新一代数字化的售后服务体系，提升企业竞争力和用户美誉度。结合全渠道服务体系、移动应用实现服务过程管理、配件全程追溯、从售后服务到用户经营以及基于用户数据分析等功能，使生产厂商能够利用更便捷的方式，对售后服务的人员和配件进行追踪、管理和评价。</p>',
			'regurl':[{'regname':'报名即将开始','reglink':'http://www.microsoft.com/China/cloudproductivity/Dynamics365webnar.html'}],
			'gallery': ['']
		},{ 
			'name':'Dynamics 合作伙伴 嘉宾访谈室-全渠道数字化营销管理解决方案',
			'contenttype': 'article',
			'logo':'guest_236x144.jpg',
			'banner':'guest_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年5月23日',
			'eventtime':'',
			'expirydate':'2017-05-23T23:59:00+08:00',
			'location':'在线会议',
			'eventfor': ['销售和市场专业人员','IT专业人员','开发人员','教育工作者','中小型企业经营者','业务管理者','IT管理者','CXO Leadership','技术管理者'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Dynamics'],
			'description': '<p>统一会员数据库：多渠道会员数据统一识别，建立360度的会员视图。<br />规范会员管理体系：建立完善的会员忠诚度计划和积分体系， 提升会员复购和会员忠诚度。<br />多渠道互动与关怀：建立各种客户关怀机制 ( 生日福利、周年日福利、节日关怀等)，提升客户体验。<br />基于微信、短信、APP等多渠道的客户连接和互动，提升客户粘性。<br />客户细分与精准营销：通过标签实现客户精细化管理，基于目标客户进行生命周期的关怀与营销。</p>',
			'regurl':[{'regname':'报名即将开始','reglink':'http://www.microsoft.com/China/cloudproductivity/Dynamics365webnar.html'}],
			'gallery': ['']
		},{ 
			'name':'Dynamics 合作伙伴 嘉宾访谈室-项目型销售管理解决方案',
			'contenttype': 'article',
			'logo':'guest_236x144.jpg',
			'banner':'guest_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年5月11日',
			'eventtime':'',
			'expirydate':'2017-05-11T23:59:00+08:00',
			'location':'在线会议',
			'eventfor': ['销售和市场专业人员','IT专业人员','开发人员','教育工作者','中小型企业经营者','业务管理者','IT管理者','CXO Leadership','技术管理者'],
			'eventtype': ['研讨会及会议'],
			'category': ['网络研讨会'],
			'product': ['Microsoft Dynamics'],
			'description': '<p>与传统的产品型销售方式相比，项目型销售管理通常体现为长周期、团队销售、方案式提供产品与服务等典型特点。<br />马上登记参加本次活动，来看看业界一流的移动化，协同化，平台化，社交化，分析化CRM系统是如何帮助企业解决业务数据的各区域协同，统一管理客户、项目信息并能够迅速指导销售，提高销售成单率，完善客户资产的管理和提升企业整体销售业绩。</p>',
			'regurl':[{'regname':'报名即将开始','reglink':'http://www.microsoft.com/China/cloudproductivity/Dynamics365webnar.html'}],
			'gallery': ['']
		},{ 
			'name':'Dynamics UG',
			'contenttype': 'article',
			'logo':'Dynamics community _236x144.jpg',
			'banner':'Dynamics community_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年5月16日',
			'eventtime':'',
			'expirydate':'2017-05-16T23:59:00+08:00',
			'location':'上海',
			'eventfor': ['销售和市场专业人员','IT专业人员','开发人员','教育工作者','中小型企业经营者','业务管理者','IT管理者','CXO Leadership','技术管理者'],
			'eventtype': ['研讨会及会议'],
			'category': ['线下会议'],
			'product': ['Microsoft Dynamics'],
			'description': '<p>微软 Dynamics 用户社区 (Microsoft Dynamics UG) 是面向微软Dynamics用户群体建立的官方学习、分享平台。社区秉持用户驱动、服务至上的理念，致力于为社区成员提供丰富产品资源与全新社区体验。在美国，微软 Dynamics 用户社区系统已极为健全，每年定期为用户举办大型培训集会，以此为蓝本，2017年微软（中国）Dynamics 用户社区正式成立！ <br />我们还组建了由用户和微软合作伙伴成员代表共同参与的社区顾问委员会，并将定期举办现场会议，邀请嘉宾分享Dynamics使用经验，用户可以自愿报名参加。随着更多新成员的加入，社区必将迎来更多的知识分享盛事，惠及所有成员。 <br />目前UG是全球最大Dynamics的用户组织，由最终用户自发组织，由行业有经验的专家自愿贡献知识和经验的非营利机构，与会人员本着务实中立的态度，禁止推介产品，服务以及其他营销行为。</p>',
			'regurl':[{'regname':'报名即将开始','reglink':'https://www.microsoft.com/China/cloudproductivity/usergroup/'}],
			'gallery': ['']
		},{ 
			'name':'Dynamics行业解决方案巡展 - 中国智造',
			'contenttype': 'article',
			'logo':'Rektec_CRM_M.jpg',
			'banner':'Rektec_CRM_DESTOP.png',
			'youtubeurl': '',
			'eventdate':'2017年5月24日',
			'eventtime':'',
			'expirydate':'2017-05-24T23:59:00+08:00',
			'location':'上海',
			'eventfor': ['销售和市场专业人员','IT专业人员','开发人员','教育工作者','中小型企业经营者','业务管理者','IT管理者','CXO Leadership','技术管理者'],
			'eventtype': ['研讨会及会议'],
			'category': ['线下会议'],
			'product': ['Microsoft Dynamics'],
			'description': '<p>微软Dynamics CRM 在全球长期占据市场领导地位，瑞泰信息作为微软Dynamics CRM金牌合作伙伴，经过10多年经验积累及行业研究，在微软Dynamics CRM 平台上搭建ServiceOne解决方案，成功为众多客户提供包括服务管理，配件管理，呼叫中心整合，移动应用在内的完整服务管理体系。</p>',
			'regurl':[{'regname':'立即报名','reglink':'http://d9.rrxiu.me/v/35t5pj?from_code=f7309e65f9f082f633c55caabe72042e'}],
			'gallery': ['']
		},{ 
			'name':'Dynamics行业解决方案巡展 - 新零售',
			'contenttype': 'article',
			'logo':'new retail_236x144.jpg',
			'banner':'new retail_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年5月23日',
			'eventtime':'',
			'expirydate':'2017-05-23T23:59:00+08:00',
			'location':'上海',
			'eventfor': ['销售和市场专业人员','IT专业人员','开发人员','教育工作者','中小型企业经营者','业务管理者','IT管理者','CXO Leadership','技术管理者'],
			'eventtype': ['研讨会及会议'],
			'category': ['线下会议'],
			'product': ['Microsoft Dynamics'],
			'description': '<p>SYSTEX是微软在中国最大的解决方案合作伙伴之一，随着行业和技术发展，新零售转型已经成为零售行业未来的趋势。精诚打造了基于微软平台的新零售解决方案，并通过利用微软Dynamics 365和Azure的业务分析能力为客户新零售转型提供稳定灵活的业务平台。</p>',
			'regurl':[{'regname':'报名即将开始','reglink':'https://www.microsoft.com/China/cloudproductivity/Dynamics365webnar.html'}],
			'gallery': ['']
		},{ 
			'name':'Dynamics行业解决方案巡展 - 财富管理行业',
			'contenttype': 'article',
			'logo':'Shenzhen TPM_236x144.jpg',
			'banner':'Shenzhen TPM_630x234.jpg',
			'youtubeurl': '',
			'eventdate':'2017年4月26日',
			'eventtime':'',
			'expirydate':'2017-04-26T23:59:00+08:00',
			'location':'深圳',
			'eventfor': ['销售和市场专业人员','IT专业人员','开发人员','教育工作者','中小型企业经营者','业务管理者','IT管理者','CXO Leadership','技术管理者'],
			'eventtype': ['研讨会及会议'],
			'category': ['线下会议'],
			'product': ['Microsoft Dynamics'],
			'description': '<p>金融行业是Dynamics CRM很有优势的行业，目前我们有中国银行，中金国际，浦发银行等大型客户，也有南区的小牛资本，鹏华基金，招商信诺，还有其它区域的金城财富，上海信托等一批大客户，微扬在这个行业有专业的团队和案例。</p>',
			'regurl':[{'regname':'立即报名','reglink':'http://www.vyung.com/col.jsp?id=151&'}],
			'gallery': ['']
		}
];


var db_filter = [
       { 
			'section':'活动受众人群',
			'type':'eventfor',
			'filter': [
			              {'type':'eventfor','name':'销售和市场专业人员'}, 
						  {'type':'eventfor','name':'IT专业人员'}, 
						  {'type':'eventfor','name':'开发人员'}, 
						  {'type':'eventfor','name':'教育工作者'}, 
						  {'type':'eventfor','name':'中小型企业经营者'},
			   	          {'type':'eventfor','name':'业务管理者'},
						  {'type':'eventfor','name':'IT管理者'},
						  {'type':'eventfor','name':'CXO Leadership'},
						  {'type':'eventfor','name':'新客戶'},
						  {'type':'eventfor','name':'Azure客戶'},
						  {'type':'eventfor','name':'合作伙伴'}
			]
	   }
	   ,{ 
			'section':'活动分类',
			'type':'eventtype',
			'filter': [
			              {'type':'eventtype','name':'技术培训'}, 
						  {'type':'eventtype','name':'研讨会及会议'},
						  {'type':'eventtype','name':'在线会议回放'},
						  {'type':'eventtype','name':'解决方案演示'}
			]
	   }
	   ,{ 
			'section':'活动形式',
			'type':'category',
			'filter': [
			              {'type':'category','name':'线下会议'},
						  {'type':'category','name':'网络研讨会'}
			]
	   }
	   ,{ 
			'section':'活动时间',
			'type':'eventtime',
			'filter': [
			              {'type':'eventtime','name':'即将发生'}, 
						  {'type':'eventtime','name':'以往活动'}
			]
	   }
	   ,{ 
			'section':'产品分类',
			'type':'product',
			'filter': [
			              {'type':'product','name':'Developer Tools'},
						  {'type':'product','name':'Devices & Xbox'},
						  {'type':'product','name':'HoloLens'},
						  {'type':'product','name':'Microsoft Azure'},
						  {'type':'product','name':'Microsoft Dynamics'},
						  {'type':'product','name':'Office'},
						  {'type':'product','name':'Power BI'},
						  {'type':'product','name':'Server and Management'},
						  {'type':'product','name':'Skype'},
						  {'type':'product','name':'Windows'},
						  {'type':'product','name':'C+E'},
						  {'type':'product','name':'Exchange'},
						  {'type':'product','name':'Internet of Things'},
						  {'type':'product','name':'Sharepoint'}
			]
	   }
];

var db_banner = [
       { 
			'desktopbanner':'Ms_ignite_china_v2_1440x300_firework.jpg',
			'mobilebanner':'Ms_ignite_china_640x553_firework.jpg',
			'url':'https://www.microsoft.com/china/ignite/2016/'
	   },
	   { 
			'desktopbanner':'Azure_1RMB_trial_1440x300.jpg',
			'mobilebanner':'Azure_1RMB_trial_414x358.jpg',
			'url':'https://www.azure.cn/pricing/1rmb-trial-full/?form-type=identityauth'
	   }
];

var db_promotion = []

